class AmusementParkRunner {

    public static void main(String[] args) {

        System.out.println("THE MAIN STARTED");

        AmusementPark a1 = new AmusementPark();
        a1.parkId = 1;
        a1.name ="Wonderla";
        a1.location = "Bangalore";
        a1.noOfRides = 50;
        a1.hasWaterPark = true;
        a1.entryFee = 1300.50;
        a1.openSeason = "All Year";
        System.out.println("Park ID: " + a1.parkId);
        System.out.println("Name: " + a1.name);
        System.out.println("Location: " + a1.location);
        System.out.println("Number of Rides: " + a1.noOfRides);
        System.out.println("Has Water Park: " + a1.hasWaterPark);
        System.out.println("Entry Fee: " + a1.entryFee);
        System.out.println("Open Season: " + a1.openSeason);

        AmusementPark a2 = new AmusementPark();
        a2.parkId = 2;
        a2.name = "Imagicaa";
        a2.location = "Mumbai";
        a2.noOfRides = 35;
        a2.hasWaterPark = true;
        a2.entryFee = 1500;
        a2.openSeason = "Winter";
        System.out.println("Park ID: " + a2.parkId);
        System.out.println("Name: " + a2.name);
        System.out.println("Location: " + a2.location);
        System.out.println("Number of Rides: " + a2.noOfRides);
        System.out.println("Has Water Park: " + a2.hasWaterPark);
        System.out.println("Entry Fee: " + a2.entryFee);
        System.out.println("Open Season: " + a2.openSeason);

        AmusementPark a3 = new AmusementPark();
        a3.parkId = 3;
        a3.name = "Essel World";
        a3.location = "Mumbai";
        a3.noOfRides = 40;
        a3.hasWaterPark = true;
        a3.entryFee = 1100;
        a3.openSeason = "Summer";
        System.out.println("Park ID: " + a3.parkId);
        System.out.println("Name: " + a3.name);
        System.out.println("Location: " + a3.location);
        System.out.println("Number of Rides: " + a3.noOfRides);
        System.out.println("Has Water Park: " + a3.hasWaterPark);
        System.out.println("Entry Fee: " + a3.entryFee);
        System.out.println("Open Season: " + a3.openSeason);

        AmusementPark a4 = new AmusementPark();
        a4.parkId = 4;
        a4.name = "Ramoji Film City";
        a4.location = "Hyderabad";
        a4.noOfRides = 30;
        a4.hasWaterPark = false;
        a4.entryFee = 1000;
        a4.openSeason = "All Year";
        System.out.println("Park ID: " + a4.parkId);
        System.out.println("Name: " + a4.name);
        System.out.println("Location: " + a4.location);
        System.out.println("Number of Rides: " + a4.noOfRides);
        System.out.println("Has Water Park: " + a4.hasWaterPark);
        System.out.println("Entry Fee: " + a4.entryFee);
        System.out.println("Open Season: " + a4.openSeason);

        AmusementPark a5 = new AmusementPark();
        a5.parkId = 5;
        a5.name = "Nicco Park";
        a5.location = "Kolkata";
        a5.noOfRides = 20;
        a5.hasWaterPark = false;
        a5.entryFee = 600;
        a5.openSeason = "Summer";
        System.out.println("Park ID: " + a5.parkId);
        System.out.println("Name: " + a5.name);
        System.out.println("Location: " + a5.location);
        System.out.println("Number of Rides: " + a5.noOfRides);
        System.out.println("Has Water Park: " + a5.hasWaterPark);
        System.out.println("Entry Fee: " + a5.entryFee);
        System.out.println("Open Season: " + a5.openSeason);
  
                AmusementPark a6 = new AmusementPark();
        a6.parkId = 6;
        a6.name = "Adventure Island";
        a6.location = "Delhi";
        a6.noOfRides = 25;
        a6.hasWaterPark = true;
        a6.entryFee = 900;
        a6.openSeason = "Monsoon";
        System.out.println("Park ID: " + a6.parkId);
        System.out.println("Name: " + a6.name);
        System.out.println("Location: " + a6.location);
        System.out.println("Number of Rides: " + a6.noOfRides);
        System.out.println("Has Water Park: " + a6.hasWaterPark);
        System.out.println("Entry Fee: " + a6.entryFee);
        System.out.println("Open Season: " + a6.openSeason);

        AmusementPark a7 = new AmusementPark();
        a7.parkId = 7;
        a7.name = "Kingdom of Dreams";
        a7.location = "Gurgaon";
        a7.noOfRides = 18;
        a7.hasWaterPark = false;
        a7.entryFee = 850;
        a7.openSeason = "All Year";
        System.out.println("Park ID: " + a7.parkId);
        System.out.println("Name: " + a7.name);
        System.out.println("Location: " + a7.location);
        System.out.println("Number of Rides: " + a7.noOfRides);
        System.out.println("Has Water Park: " + a7.hasWaterPark);
        System.out.println("Entry Fee: " + a7.entryFee);
        System.out.println("Open Season: " + a7.openSeason);

        AmusementPark a8 = new AmusementPark();
        a8.parkId = 8;
        a8.name = "Ocean Park";
        a8.location = "Hyderabad";
        a8.noOfRides = 22;
        a8.hasWaterPark = true;
        a8.entryFee = 700;
        a8.openSeason = "Summer";
        System.out.println("Park ID: " + a8.parkId);
        System.out.println("Name: " + a8.name);
        System.out.println("Location: " + a8.location);
        System.out.println("Number of Rides: " + a8.noOfRides);
        System.out.println("Has Water Park: " + a8.hasWaterPark);
        System.out.println("Entry Fee: " + a8.entryFee);
        System.out.println("Open Season: " + a8.openSeason);

        AmusementPark a9 = new AmusementPark();
        a9.parkId = 9;
        a9.name = "Snow World";
        a9.location = "Hyderabad";
        a9.noOfRides = 10;
        a9.hasWaterPark = false;
        a9.entryFee = 500;
        a9.openSeason = "Winter";
        System.out.println("Park ID: " + a9.parkId);
        System.out.println("Name: " + a9.name);
        System.out.println("Location: " + a9.location);
        System.out.println("Number of Rides: " + a9.noOfRides);
        System.out.println("Has Water Park: " + a9.hasWaterPark);
        System.out.println("Entry Fee: " + a9.entryFee);
        System.out.println("Open Season: " + a9.openSeason);

        AmusementPark a10 = new AmusementPark();
        a10.parkId = 10;
        a10.name = "Funtasia Island";
        a10.location = "Patna";
        a10.noOfRides = 15;
        a10.hasWaterPark = true;
        a10.entryFee = 650;
        a10.openSeason = "All Year";
        System.out.println("Park ID: " + a10.parkId);
        System.out.println("Name: " + a10.name);
        System.out.println("Location: " + a10.location);
        System.out.println("Number of Rides: " + a10.noOfRides);
        System.out.println("Has Water Park: " + a10.hasWaterPark);
        System.out.println("Entry Fee: " + a10.entryFee);
        System.out.println("Open Season: " + a10.openSeason);

        AmusementPark a11 = new AmusementPark();
        a11.parkId = 11;
        a11.name = "Jurasik Park Inn";
        a11.location = "Sonipat";
        a11.noOfRides = 28;
        a11.hasWaterPark = true;
        a11.entryFee = 1000;
        a11.openSeason = "Spring";
        System.out.println("Park ID: " + a11.parkId);
        System.out.println("Name: " + a11.name);
        System.out.println("Location: " + a11.location);
        System.out.println("Number of Rides: " + a11.noOfRides);
        System.out.println("Has Water Park: " + a11.hasWaterPark);
        System.out.println("Entry Fee: " + a11.entryFee);
        System.out.println("Open Season: " + a11.openSeason);

        AmusementPark a12 = new AmusementPark();
        a12.parkId = 12;
        a12.name = "Fantasy Land";
        a12.location = "Mumbai";
        a12.noOfRides = 16;
        a12.hasWaterPark = false;
        a12.entryFee = 550;
        a12.openSeason = "Autumn";
        System.out.println("Park ID: " + a12.parkId);
        System.out.println("Name: " + a12.name);
        System.out.println("Location: " + a12.location);
        System.out.println("Number of Rides: " + a12.noOfRides);
        System.out.println("Has Water Park: " + a12.hasWaterPark);
        System.out.println("Entry Fee: " + a12.entryFee);
        System.out.println("Open Season: " + a12.openSeason);

        AmusementPark a13 = new AmusementPark();
        a13.parkId = 13;
        a13.name = "Fun City";
        a13.location = "Chandigarh";
        a13.noOfRides = 19;
        a13.hasWaterPark = true;
        a13.entryFee = 800;
        a13.openSeason = "All Year";
        System.out.println("Park ID: " + a13.parkId);
        System.out.println("Name: " + a13.name);
        System.out.println("Location: " + a13.location);
        System.out.println("Number of Rides: " + a13.noOfRides);
        System.out.println("Has Water Park: " + a13.hasWaterPark);
        System.out.println("Entry Fee: " + a13.entryFee);
        System.out.println("Open Season: " + a13.openSeason);

        AmusementPark a14 = new AmusementPark();
        a14.parkId = 14;
        a14.name = "Dream World";
        a14.location = "Thrissur";
        a14.noOfRides = 26;
        a14.hasWaterPark = true;
        a14.entryFee = 950;
        a14.openSeason = "All Year";
        System.out.println("Park ID: " + a14.parkId);
        System.out.println("Name: " + a14.name);
        System.out.println("Location: " + a14.location);
        System.out.println("Number of Rides: " + a14.noOfRides);
        System.out.println("Has Water Park: " + a14.hasWaterPark);
        System.out.println("Entry Fee: " + a14.entryFee);
        System.out.println("Open Season: " + a14.openSeason);

        AmusementPark a15 = new AmusementPark();
        a15.parkId = 15;
        a15.name = "Vismaya";
        a15.location = "Kannur";
        a15.noOfRides = 23;
        a15.hasWaterPark = true;
        a15.entryFee = 720;
        a15.openSeason = "Winter";
        System.out.println("Park ID: " + a15.parkId);
        System.out.println("Name: " + a15.name);
        System.out.println("Location: " + a15.location);
        System.out.println("Number of Rides: " + a15.noOfRides);
        System.out.println("Has Water Park: " + a15.hasWaterPark);
        System.out.println("Entry Fee: " + a15.entryFee);
        System.out.println("Open Season: " + a15.openSeason);

        AmusementPark a16 = new AmusementPark();
        a16.parkId = 16;
        a16.name = "Aquatica";
        a16.location = "Kolkata";
        a16.noOfRides = 17;
        a16.hasWaterPark = true;
        a16.entryFee = 880;
        a16.openSeason = "Summer";
        System.out.println("Park ID: " + a16.parkId);
        System.out.println("Name: " + a16.name);
        System.out.println("Location: " + a16.location);
        System.out.println("Number of Rides: " + a16.noOfRides);
        System.out.println("Has Water Park: " + a16.hasWaterPark);
        System.out.println("Entry Fee: " + a16.entryFee);
        System.out.println("Open Season: " + a16.openSeason);

        AmusementPark a17 = new AmusementPark();
        a17.parkId = 17;
        a17.name = "Splash The Water Park";
        a17.location = "Delhi";
        a17.noOfRides = 12;
        a17.hasWaterPark = true;
        a17.entryFee = 750;
        a17.openSeason = "Summer";
        System.out.println("Park ID: " + a17.parkId);
        System.out.println("Name: " + a17.name);
        System.out.println("Location: " + a17.location);
        System.out.println("Number of Rides: " + a17.noOfRides);
        System.out.println("Has Water Park: " + a17.hasWaterPark);
        System.out.println("Entry Fee: " + a17.entryFee);
        System.out.println("Open Season: " + a17.openSeason);

        AmusementPark a18 = new AmusementPark();
        a18.parkId = 18;
        a18.name = "Appu Ghar";
        a18.location = "Gurgaon";
        a18.noOfRides = 21;
        a18.hasWaterPark = true;
        a18.entryFee = 990;
        a18.openSeason = "All Year";
        System.out.println("Park ID: " + a18.parkId);
        System.out.println("Name: " + a18.name);
        System.out.println("Location: " + a18.location);
        System.out.println("Number of Rides: " + a18.noOfRides);
        System.out.println("Has Water Park: " + a18.hasWaterPark);
        System.out.println("Entry Fee: " + a18.entryFee);
        System.out.println("Open Season: " + a18.openSeason);

        AmusementPark a19 = new AmusementPark();
        a19.parkId = 19;
        a19.name = "Worlds of Wonder";
        a19.location = "Noida";
        a19.noOfRides = 24;
        a19.hasWaterPark = true;
        a19.entryFee = 1050;
        a19.openSeason = "Winter";
        System.out.println("Park ID: " + a19.parkId);
        System.out.println("Name: " + a19.name);
        System.out.println("Location: " + a19.location);
        System.out.println("Number of Rides: " + a19.noOfRides);
        System.out.println("Has Water Park: " + a19.hasWaterPark);
        System.out.println("Entry Fee: " + a19.entryFee);
        System.out.println("Open Season: " + a19.openSeason);

        AmusementPark a20 = new AmusementPark();
        a20.parkId = 20;
        a20.name = "Wet N Joy";
        a20.location = "Lonavala";
        a20.noOfRides = 27;
        a20.hasWaterPark = true;
        a20.entryFee = 1150;
        a20.openSeason = "All Year";
        System.out.println("Park ID: " + a20.parkId);
        System.out.println("Name: " + a20.name);
        System.out.println("Location: " + a20.location);
        System.out.println("Number of Rides: " + a20.noOfRides);
        System.out.println("Has Water Park: " + a20.hasWaterPark);
        System.out.println("Entry Fee: " + a20.entryFee);
        System.out.println("Open Season: " + a20.openSeason);

        

        System.out.println("THE MAIN ENDED");
    }
}
