class BeltRunner {

    public static void main(String[] args) {
        System.out.println("THE MAIN STARTED");

        Belt belt1 = new Belt();
        belt1.beltId = 1;
        belt1.brand = "Levis";
        belt1.material = "Leather";
        belt1.color = "Black";
        belt1.length = 38.0;
        belt1.isReversible = false;
        belt1.price = 1499.99;
        System.out.println("Belt ID: " + belt1.beltId);
        System.out.println("Brand: " + belt1.brand);
        System.out.println("Material: " + belt1.material);
        System.out.println("Color: " + belt1.color);
        System.out.println("Length: " + belt1.length + " inches");
        System.out.println("Reversible: " + belt1.isReversible);
        System.out.println("Price: ₹" + belt1.price);

        Belt belt2 = new Belt();
        belt2.beltId = 2;
        belt2.brand = "Puma";
        belt2.material = "Canvas";
        belt2.color = "Brown";
        belt2.length = 40.0;
        belt2.isReversible = true;
        belt2.price = 899.00;
        System.out.println("Belt ID: " + belt2.beltId);
        System.out.println("Brand: " + belt2.brand);
        System.out.println("Material: " + belt2.material);
        System.out.println("Color: " + belt2.color);
        System.out.println("Length: " + belt2.length + " inches");
        System.out.println("Reversible: " + belt2.isReversible);
        System.out.println("Price: ₹" + belt2.price);

        Belt belt3 = new Belt();
        belt3.beltId = 3;
        belt3.brand = "Gucci";
        belt3.material = "Synthetic";
        belt3.color = "Grey";
        belt3.length = 36.0;
        belt3.isReversible = true;
        belt3.price = 2999.50;
        System.out.println("Belt ID: " + belt3.beltId);
        System.out.println("Brand: " + belt3.brand);
        System.out.println("Material: " + belt3.material);
        System.out.println("Color: " + belt3.color);
        System.out.println("Length: " + belt3.length + " inches");
        System.out.println("Reversible: " + belt3.isReversible);
        System.out.println("Price: ₹" + belt3.price);

         Belt belt4 = new Belt();
        belt4.beltId = 4;
        belt4.brand = "Wrangler";
        belt4.material = "Leather";
        belt4.color = "Tan";
        belt4.length = 39.5;
        belt4.isReversible = false;
        belt4.price = 1299.00;
        System.out.println("Belt ID: " + belt4.beltId);
        System.out.println("Brand: " + belt4.brand);
        System.out.println("Material: " + belt4.material);
        System.out.println("Color: " + belt4.color);
        System.out.println("Length: " + belt4.length + " inches");
        System.out.println("Reversible: " + belt4.isReversible);
        System.out.println("Price: ₹" + belt4.price);

        Belt belt5 = new Belt();
        belt5.beltId = 5;
        belt5.brand = "Nike";
        belt5.material = "Canvas";
        belt5.color = "Olive Green";
        belt5.length = 42.0;
        belt5.isReversible = true;
        belt5.price = 1099.99;
        System.out.println("Belt ID: " + belt5.beltId);
        System.out.println("Brand: " + belt5.brand);
        System.out.println("Material: " + belt5.material);
        System.out.println("Color: " + belt5.color);
        System.out.println("Length: " + belt5.length + " inches");
        System.out.println("Reversible: " + belt5.isReversible);
        System.out.println("Price: ₹" + belt5.price);

        Belt belt6 = new Belt();
        belt6.beltId = 6;
        belt6.brand = "Zara";
        belt6.material = "Faux Leather";
        belt6.color = "White";
        belt6.length = 37.0;
        belt6.isReversible = false;
        belt6.price = 899.00;
        System.out.println("Belt ID: " + belt6.beltId);
        System.out.println("Brand: " + belt6.brand);
        System.out.println("Material: " + belt6.material);
        System.out.println("Color: " + belt6.color);
        System.out.println("Length: " + belt6.length + " inches");
        System.out.println("Reversible: " + belt6.isReversible);
        System.out.println("Price: ₹" + belt6.price);

        Belt belt7 = new Belt();
        belt7.beltId = 7;
        belt7.brand = "Allen Solly";
        belt7.material = "Leather";
        belt7.color = "Dark Brown";
        belt7.length = 38.5;
        belt7.isReversible = false;
        belt7.price = 1599.00;
        System.out.println("Belt ID: " + belt7.beltId);
        System.out.println("Brand: " + belt7.brand);
        System.out.println("Material: " + belt7.material);
        System.out.println("Color: " + belt7.color);
        System.out.println("Length: " + belt7.length + " inches");
        System.out.println("Reversible: " + belt7.isReversible);
        System.out.println("Price: ₹" + belt7.price);

        Belt belt8 = new Belt();
        belt8.beltId = 8;
        belt8.brand = "HRX";
        belt8.material = "Synthetic";
        belt8.color = "Grey";
        belt8.length = 40.0;
        belt8.isReversible = true;
        belt8.price = 999.00;
        System.out.println("Belt ID: " + belt8.beltId);
        System.out.println("Brand: " + belt8.brand);
        System.out.println("Material: " + belt8.material);
        System.out.println("Color: " + belt8.color);
        System.out.println("Length: " + belt8.length + " inches");
        System.out.println("Reversible: " + belt8.isReversible);
        System.out.println("Price: ₹" + belt8.price);

        Belt belt9 = new Belt();
        belt9.beltId = 9;
        belt9.brand = "Van Heusen";
        belt9.material = "Canvas";
        belt9.color = "Khaki";
        belt9.length = 41.0;
        belt9.isReversible = false;
        belt9.price = 1199.00;
        System.out.println("Belt ID: " + belt9.beltId);
        System.out.println("Brand: " + belt9.brand);
        System.out.println("Material: " + belt9.material);
        System.out.println("Color: " + belt9.color);
        System.out.println("Length: " + belt9.length + " inches");
        System.out.println("Reversible: " + belt9.isReversible);
        System.out.println("Price: ₹" + belt9.price);

        Belt belt10 = new Belt();
        belt10.beltId = 10;
        belt10.brand = "Reebok";
        belt10.material = "Synthetic";
        belt10.color = "Blue";
        belt10.length = 36.0;
        belt10.isReversible = true;
        belt10.price = 1050.00;
        System.out.println("Belt ID: " + belt10.beltId);
        System.out.println("Brand: " + belt10.brand);
        System.out.println("Material: " + belt10.material);
        System.out.println("Color: " + belt10.color);
        System.out.println("Length: " + belt10.length + " inches");
        System.out.println("Reversible: " + belt10.isReversible);
        System.out.println("Price: ₹" + belt10.price);

                Belt belt11 = new Belt();
        belt11.beltId = 11;
        belt11.brand = "Superdry";
        belt11.material = "Leather";
        belt11.color = "Charcoal Black";
        belt11.length = 42.5;
        belt11.isReversible = true;
        belt11.price = 1799.00;
        System.out.println("Belt ID: " + belt11.beltId);
        System.out.println("Brand: " + belt11.brand);
        System.out.println("Material: " + belt11.material);
        System.out.println("Color: " + belt11.color);
        System.out.println("Length: " + belt11.length + " inches");
        System.out.println("Reversible: " + belt11.isReversible);
        System.out.println("Price: ₹" + belt11.price);

        Belt belt12 = new Belt();
        belt12.beltId = 12;
        belt12.brand = "Raymond";
        belt12.material = "Synthetic Leather";
        belt12.color = "Black";
        belt12.length = 37.5;
        belt12.isReversible = false;
        belt12.price = 950.00;
        System.out.println("Belt ID: " + belt12.beltId);
        System.out.println("Brand: " + belt12.brand);
        System.out.println("Material: " + belt12.material);
        System.out.println("Color: " + belt12.color);
        System.out.println("Length: " + belt12.length + " inches");
        System.out.println("Reversible: " + belt12.isReversible);
        System.out.println("Price: ₹" + belt12.price);

        Belt belt13 = new Belt();
        belt13.beltId = 13;
        belt13.brand = "Diesel";
        belt13.material = "Denim";
        belt13.color = "Denim Blue";
        belt13.length = 38.0;
        belt13.isReversible = false;
        belt13.price = 1600.00;
        System.out.println("Belt ID: " + belt13.beltId);
        System.out.println("Brand: " + belt13.brand);
        System.out.println("Material: " + belt13.material);
        System.out.println("Color: " + belt13.color);
        System.out.println("Length: " + belt13.length + " inches");
        System.out.println("Reversible: " + belt13.isReversible);
        System.out.println("Price: ₹" + belt13.price);

        Belt belt14 = new Belt();
        belt14.beltId = 14;
        belt14.brand = "H&M";
        belt14.material = "Canvas";
        belt14.color = "Beige";
        belt14.length = 40.5;
        belt14.isReversible = true;
        belt14.price = 850.00;
        System.out.println("Belt ID: " + belt14.beltId);
        System.out.println("Brand: " + belt14.brand);
        System.out.println("Material: " + belt14.material);
        System.out.println("Color: " + belt14.color);
        System.out.println("Length: " + belt14.length + " inches");
        System.out.println("Reversible: " + belt14.isReversible);
        System.out.println("Price: ₹" + belt14.price);

        Belt belt15 = new Belt();
        belt15.beltId = 15;
        belt15.brand = "US Polo";
        belt15.material = "Leather";
        belt15.color = "Chestnut";
        belt15.length = 41.0;
        belt15.isReversible = true;
        belt15.price = 1250.00;
        System.out.println("Belt ID: " + belt15.beltId);
        System.out.println("Brand: " + belt15.brand);
        System.out.println("Material: " + belt15.material);
        System.out.println("Color: " + belt15.color);
        System.out.println("Length: " + belt15.length + " inches");
        System.out.println("Reversible: " + belt15.isReversible);
        System.out.println("Price: ₹" + belt15.price);

        Belt belt16 = new Belt();
        belt16.beltId = 16;
        belt16.brand = "Flying Machine";
        belt16.material = "Faux Leather";
        belt16.color = "Camel";
        belt16.length = 39.0;
        belt16.isReversible = false;
        belt16.price = 990.00;
        System.out.println("Belt ID: " + belt16.beltId);
        System.out.println("Brand: " + belt16.brand);
        System.out.println("Material: " + belt16.material);
        System.out.println("Color: " + belt16.color);
        System.out.println("Length: " + belt16.length + " inches");
        System.out.println("Reversible: " + belt16.isReversible);
        System.out.println("Price: ₹" + belt16.price);

        Belt belt17 = new Belt();
        belt17.beltId = 17;
        belt17.brand = "Puma";
        belt17.material = "Fabric";
        belt17.color = "Army Green";
        belt17.length = 43.0;
        belt17.isReversible = false;
        belt17.price = 799.00;
        System.out.println("Belt ID: " + belt17.beltId);
        System.out.println("Brand: " + belt17.brand);
        System.out.println("Material: " + belt17.material);
        System.out.println("Color: " + belt17.color);
        System.out.println("Length: " + belt17.length + " inches");
        System.out.println("Reversible: " + belt17.isReversible);
        System.out.println("Price: ₹" + belt17.price);

        Belt belt18 = new Belt();
        belt18.beltId = 18;
        belt18.brand = "Fossil";
        belt18.material = "Leather";
        belt18.color = "Vintage Brown";
        belt18.length = 39.5;
        belt18.isReversible = true;
        belt18.price = 2100.00;
        System.out.println("Belt ID: " + belt18.beltId);
        System.out.println("Brand: " + belt18.brand);
        System.out.println("Material: " + belt18.material);
        System.out.println("Color: " + belt18.color);
        System.out.println("Length: " + belt18.length + " inches");
        System.out.println("Reversible: " + belt18.isReversible);
        System.out.println("Price: ₹" + belt18.price);

        Belt belt19 = new Belt();
        belt19.beltId = 19;
        belt19.brand = "Hidesign";
        belt19.material = "Genuine Leather";
        belt19.color = "Ox Blood";
        belt19.length = 38.0;
        belt19.isReversible = false;
        belt19.price = 1950.00;
        System.out.println("Belt ID: " + belt19.beltId);
        System.out.println("Brand: " + belt19.brand);
        System.out.println("Material: " + belt19.material);
        System.out.println("Color: " + belt19.color);
        System.out.println("Length: " + belt19.length + " inches");
        System.out.println("Reversible: " + belt19.isReversible);
        System.out.println("Price: ₹" + belt19.price);

        Belt belt20 = new Belt();
        belt20.beltId = 20;
        belt20.brand = "Levi's";
        belt20.material = "Nylon";
        belt20.color = "Navy Blue";
        belt20.length = 36.0;
        belt20.isReversible = true;
        belt20.price = 870.00;
        System.out.println("Belt ID: " + belt20.beltId);
        System.out.println("Brand: " + belt20.brand);
        System.out.println("Material: " + belt20.material);
        System.out.println("Color: " + belt20.color);
        System.out.println("Length: " + belt20.length + " inches");
        System.out.println("Reversible: " + belt20.isReversible);
        System.out.println("Price: ₹" + belt20.price);

        System.out.println("THE MAIN ENDED");

    }
}
