class BladeRunner {

    public static void main(String[] args) {
        System.out.println("THE MAIN STARTED");

        Blade blade1 = new Blade();
        blade1.bladeId = 1;
        blade1.brand = "Gillette";
        blade1.material = "Stainless Steel";
        blade1.sharpnessLevel = 9;
        blade1.lengthInCm = 4.5;
        blade1.isReusable = false;
        blade1.type = "Safety Razor";
        System.out.println("Blade ID: " + blade1.bladeId);
        System.out.println("Brand: " + blade1.brand);
        System.out.println("Material: " + blade1.material);
        System.out.println("Sharpness Level: " + blade1.sharpnessLevel);
        System.out.println("Length: " + blade1.lengthInCm + " cm");
        System.out.println("Reusable: " + blade1.isReusable);
        System.out.println("Type: " + blade1.type);

        Blade blade2 = new Blade();
        blade2.bladeId = 2;
        blade2.brand = "SuperMax";
        blade2.material = "Carbon Steel";
        blade2.sharpnessLevel = 8;
        blade2.lengthInCm = 4.2;
        blade2.isReusable = false;
        blade2.type = "Disposable";
        System.out.println("Blade ID: " + blade2.bladeId);
        System.out.println("Brand: " + blade2.brand);
        System.out.println("Material: " + blade2.material);
        System.out.println("Sharpness Level: " + blade2.sharpnessLevel);
        System.out.println("Length: " + blade2.lengthInCm + " cm");
        System.out.println("Reusable: " + blade2.isReusable);
        System.out.println("Type: " + blade2.type);

        Blade blade3 = new Blade();
        blade3.bladeId = 3;
        blade3.brand = "Wilkinson";
        blade3.material = "Titanium";
        blade3.sharpnessLevel = 9;
        blade3.lengthInCm = 4.8;
        blade3.isReusable = true;
        blade3.type = "Cartridge";
        System.out.println("Blade ID: " + blade3.bladeId);
        System.out.println("Brand: " + blade3.brand);
        System.out.println("Material: " + blade3.material);
        System.out.println("Sharpness Level: " + blade3.sharpnessLevel);
        System.out.println("Length: " + blade3.lengthInCm + " cm");
        System.out.println("Reusable: " + blade3.isReusable);
        System.out.println("Type: " + blade3.type);

        Blade blade4 = new Blade();
        blade4.bladeId = 4;
        blade4.brand = "Dorco";
        blade4.material = "Platinum";
        blade4.sharpnessLevel = 7;
        blade4.lengthInCm = 4.1;
        blade4.isReusable = false;
        blade4.type = "Straight Razor";
        System.out.println("Blade ID: " + blade4.bladeId);
        System.out.println("Brand: " + blade4.brand);
        System.out.println("Material: " + blade4.material);
        System.out.println("Sharpness Level: " + blade4.sharpnessLevel);
        System.out.println("Length: " + blade4.lengthInCm + " cm");
        System.out.println("Reusable: " + blade4.isReusable);
        System.out.println("Type: " + blade4.type);

        Blade blade5 = new Blade();
        blade5.bladeId = 5;
        blade5.brand = "Feather";
        blade5.material = "Stainless Steel";
        blade5.sharpnessLevel = 10;
        blade5.lengthInCm = 4.3;
        blade5.isReusable = true;
        blade5.type = "Straight Razor";
        System.out.println("Blade ID: " + blade5.bladeId);
        System.out.println("Brand: " + blade5.brand);
        System.out.println("Material: " + blade5.material);
        System.out.println("Sharpness Level: " + blade5.sharpnessLevel);
        System.out.println("Length: " + blade5.lengthInCm + " cm");
        System.out.println("Reusable: " + blade5.isReusable);
        System.out.println("Type: " + blade5.type);

        Blade blade6 = new Blade();
        blade6.bladeId = 6;
        blade6.brand = "Astra";
        blade6.material = "Carbon Steel";
        blade6.sharpnessLevel = 8;
        blade6.lengthInCm = 4.0;
        blade6.isReusable = false;
        blade6.type = "Safety Razor";
        System.out.println("Blade ID: " + blade6.bladeId);
        System.out.println("Brand: " + blade6.brand);
        System.out.println("Material: " + blade6.material);
        System.out.println("Sharpness Level: " + blade6.sharpnessLevel);
        System.out.println("Length: " + blade6.lengthInCm + " cm");
        System.out.println("Reusable: " + blade6.isReusable);
        System.out.println("Type: " + blade6.type);

        Blade blade7 = new Blade();
        blade7.bladeId = 7;
        blade7.brand = "KAI";
        blade7.material = "Titanium";
        blade7.sharpnessLevel = 9;
        blade7.lengthInCm = 4.6;
        blade7.isReusable = true;
        blade7.type = "Cartridge";
        System.out.println("Blade ID: " + blade7.bladeId);
        System.out.println("Brand: " + blade7.brand);
        System.out.println("Material: " + blade7.material);
        System.out.println("Sharpness Level: " + blade7.sharpnessLevel);
        System.out.println("Length: " + blade7.lengthInCm + " cm");
        System.out.println("Reusable: " + blade7.isReusable);
        System.out.println("Type: " + blade7.type);

        Blade blade8 = new Blade();
        blade8.bladeId = 8;
        blade8.brand = "Bic";
        blade8.material = "Stainless Steel";
        blade8.sharpnessLevel = 7;
        blade8.lengthInCm = 4.2;
        blade8.isReusable = false;
        blade8.type = "Disposable";
        System.out.println("Blade ID: " + blade8.bladeId);
        System.out.println("Brand: " + blade8.brand);
        System.out.println("Material: " + blade8.material);
        System.out.println("Sharpness Level: " + blade8.sharpnessLevel);
        System.out.println("Length: " + blade8.lengthInCm + " cm");
        System.out.println("Reusable: " + blade8.isReusable);
        System.out.println("Type: " + blade8.type);

        Blade blade9 = new Blade();
        blade9.bladeId = 9;
        blade9.brand = "Shick";
        blade9.material = "Platinum Coated";
        blade9.sharpnessLevel = 8;
        blade9.lengthInCm = 4.4;
        blade9.isReusable = true;
        blade9.type = "Cartridge";
        System.out.println("Blade ID: " + blade9.bladeId);
        System.out.println("Brand: " + blade9.brand);
        System.out.println("Material: " + blade9.material);
        System.out.println("Sharpness Level: " + blade9.sharpnessLevel);
        System.out.println("Length: " + blade9.lengthInCm + " cm");
        System.out.println("Reusable: " + blade9.isReusable);
        System.out.println("Type: " + blade9.type);

        Blade blade10 = new Blade();
        blade10.bladeId = 10;
        blade10.brand = "Merkur";
        blade10.material = "Stainless Steel";
        blade10.sharpnessLevel = 9;
        blade10.lengthInCm = 4.6;
        blade10.isReusable = false;
        blade10.type = "Safety Razor";
        System.out.println("Blade ID: " + blade10.bladeId);
        System.out.println("Brand: " + blade10.brand);
        System.out.println("Material: " + blade10.material);
        System.out.println("Sharpness Level: " + blade10.sharpnessLevel);
        System.out.println("Length: " + blade10.lengthInCm + " cm");
        System.out.println("Reusable: " + blade10.isReusable);
        System.out.println("Type: " + blade10.type);

        Blade blade11 = new Blade();
        blade11.bladeId = 11;
        blade11.brand = "Persona";
        blade11.material = "Carbon Steel";
        blade11.sharpnessLevel = 7;
        blade11.lengthInCm = 4.1;
        blade11.isReusable = false;
        blade11.type = "Disposable";
        System.out.println("Blade ID: " + blade11.bladeId);
        System.out.println("Brand: " + blade11.brand);
        System.out.println("Material: " + blade11.material);
        System.out.println("Sharpness Level: " + blade11.sharpnessLevel);
        System.out.println("Length: " + blade11.lengthInCm + " cm");
        System.out.println("Reusable: " + blade11.isReusable);
        System.out.println("Type: " + blade11.type);

        Blade blade12 = new Blade();
        blade12.bladeId = 12;
        blade12.brand = "Cloud";
        blade12.material = "Stainless Steel";
        blade12.sharpnessLevel = 8;
        blade12.lengthInCm = 4.0;
        blade12.isReusable = false;
        blade12.type = "Safety Razor";
        System.out.println("Blade ID: " + blade12.bladeId);
        System.out.println("Brand: " + blade12.brand);
        System.out.println("Material: " + blade12.material);
        System.out.println("Sharpness Level: " + blade12.sharpnessLevel);
        System.out.println("Length: " + blade12.lengthInCm + " cm");
        System.out.println("Reusable: " + blade12.isReusable);
        System.out.println("Type: " + blade12.type);

        Blade blade13 = new Blade();
        blade13.bladeId = 13;
        blade13.brand = "Kai Pro";
        blade13.material = "Titanium";
        blade13.sharpnessLevel = 9;
        blade13.lengthInCm = 4.7;
        blade13.isReusable = true;
        blade13.type = "Cartridge";
        System.out.println("Blade ID: " + blade13.bladeId);
        System.out.println("Brand: " + blade13.brand);
        System.out.println("Material: " + blade13.material);
        System.out.println("Sharpness Level: " + blade13.sharpnessLevel);
        System.out.println("Length: " + blade13.lengthInCm + " cm");
        System.out.println("Reusable: " + blade13.isReusable);
        System.out.println("Type: " + blade13.type);

        Blade blade14 = new Blade();
        blade14.bladeId = 14;
        blade14.brand = "Laser Ultra";
        blade14.material = "Platinum";
        blade14.sharpnessLevel = 7;
        blade14.lengthInCm = 4.3;
        blade14.isReusable = false;
        blade14.type = "Straight Razor";
        System.out.println("Blade ID: " + blade14.bladeId);
        System.out.println("Brand: " + blade14.brand);
        System.out.println("Material: " + blade14.material);
        System.out.println("Sharpness Level: " + blade14.sharpnessLevel);
        System.out.println("Length: " + blade14.lengthInCm + " cm");
        System.out.println("Reusable: " + blade14.isReusable);
        System.out.println("Type: " + blade14.type);

        Blade blade15 = new Blade();
        blade15.bladeId = 15;
        blade15.brand = "Gillette Guard";
        blade15.material = "Carbon Steel";
        blade15.sharpnessLevel = 6;
        blade15.lengthInCm = 4.1;
        blade15.isReusable = true;
        blade15.type = "Single Blade";
        System.out.println("Blade ID: " + blade15.bladeId);
        System.out.println("Brand: " + blade15.brand);
        System.out.println("Material: " + blade15.material);
        System.out.println("Sharpness Level: " + blade15.sharpnessLevel);
        System.out.println("Length: " + blade15.lengthInCm + " cm");
        System.out.println("Reusable: " + blade15.isReusable);
        System.out.println("Type: " + blade15.type);

        Blade blade16 = new Blade();
        blade16.bladeId = 16;
        blade16.brand = "Parker";
        blade16.material = "Stainless Steel";
        blade16.sharpnessLevel = 8;
        blade16.lengthInCm = 4.4;
        blade16.isReusable = false;
        blade16.type = "Safety Razor";
        System.out.println("Blade ID: " + blade16.bladeId);
        System.out.println("Brand: " + blade16.brand);
        System.out.println("Material: " + blade16.material);
        System.out.println("Sharpness Level: " + blade16.sharpnessLevel);
        System.out.println("Length: " + blade16.lengthInCm + " cm");
        System.out.println("Reusable: " + blade16.isReusable);
        System.out.println("Type: " + blade16.type);

        Blade blade17 = new Blade();
        blade17.bladeId = 17;
        blade17.brand = "Lord";
        blade17.material = "Chrome Steel";
        blade17.sharpnessLevel = 6;
        blade17.lengthInCm = 4.3;
        blade17.isReusable = false;
        blade17.type = "Disposable";
        System.out.println("Blade ID: " + blade17.bladeId);
        System.out.println("Brand: " + blade17.brand);
        System.out.println("Material: " + blade17.material);
        System.out.println("Sharpness Level: " + blade17.sharpnessLevel);
        System.out.println("Length: " + blade17.lengthInCm + " cm");
        System.out.println("Reusable: " + blade17.isReusable);
        System.out.println("Type: " + blade17.type);

        Blade blade18 = new Blade();
        blade18.bladeId = 18;
        blade18.brand = "Rapira";
        blade18.material = "Stainless Steel";
        blade18.sharpnessLevel = 7;
        blade18.lengthInCm = 4.2;
        blade18.isReusable = false;
        blade18.type = "Straight Razor";
        System.out.println("Blade ID: " + blade18.bladeId);
        System.out.println("Brand: " + blade18.brand);
        System.out.println("Material: " + blade18.material);
        System.out.println("Sharpness Level: " + blade18.sharpnessLevel);
        System.out.println("Length: " + blade18.lengthInCm + " cm");
        System.out.println("Reusable: " + blade18.isReusable);
        System.out.println("Type: " + blade18.type);

        Blade blade19 = new Blade();
        blade19.bladeId = 19;
        blade19.brand = "BigBen";
        blade19.material = "Carbon Steel";
        blade19.sharpnessLevel = 6;
        blade19.lengthInCm = 4.0;
        blade19.isReusable = false;
        blade19.type = "Single Edge";
        System.out.println("Blade ID: " + blade19.bladeId);
        System.out.println("Brand: " + blade19.brand);
        System.out.println("Material: " + blade19.material);
        System.out.println("Sharpness Level: " + blade19.sharpnessLevel);
        System.out.println("Length: " + blade19.lengthInCm + " cm");
        System.out.println("Reusable: " + blade19.isReusable);
        System.out.println("Type: " + blade19.type);

        Blade blade20 = new Blade();
        blade20.bladeId = 20;
        blade20.brand = "Shaving Factory";
        blade20.material = "Titanium";
        blade20.sharpnessLevel = 9;
        blade20.lengthInCm = 4.5;
        blade20.isReusable = true;
        blade20.type = "Cartridge";
        System.out.println("Blade ID: " + blade20.bladeId);
        System.out.println("Brand: " + blade20.brand);
        System.out.println("Material: " + blade20.material);
        System.out.println("Sharpness Level: " + blade20.sharpnessLevel);
        System.out.println("Length: " + blade20.lengthInCm + " cm");
        System.out.println("Reusable: " + blade20.isReusable);
        System.out.println("Type: " + blade20.type);

        System.out.println("THE MAIN ENDED");
    }
}




        