class CoinsRunner {

    public static void main(String[] args) {

        System.out.println("THE MAIN STARTED");

        Coins coin1 = new Coins();
        coin1.coinId = 1;
        coin1.country = "India";
        coin1.metal = "Copper";
        coin1.weight = 3.5;
        coin1.yearOfMint = 2001;
        coin1.isRare = false;
        coin1.denomination = "1 Rupee";
        System.out.println("Coin ID: " + coin1.coinId);
        System.out.println("Country: " + coin1.country);
        System.out.println("Metal: " + coin1.metal);
        System.out.println("Weight: " + coin1.weight + "g");
        System.out.println("Year of Mint: " + coin1.yearOfMint);
        System.out.println("Is Rare: " + coin1.isRare);
        System.out.println("Denomination: " + coin1.denomination);

        Coins coin2 = new Coins();
        coin2.coinId = 2;
        coin2.country = "USA";
        coin2.metal = "Silver";
        coin2.weight = 6.8;
        coin2.yearOfMint = 1950;
        coin2.isRare = true;
        coin2.denomination = "Quarter Dollar";
        System.out.println("Coin ID: " + coin2.coinId);
        System.out.println("Country: " + coin2.country);
        System.out.println("Metal: " + coin2.metal);
        System.out.println("Weight: " + coin2.weight + "g");
        System.out.println("Year of Mint: " + coin2.yearOfMint);
        System.out.println("Is Rare: " + coin2.isRare);
        System.out.println("Denomination: " + coin2.denomination);

        Coins coin3 = new Coins();
        coin3.coinId = 3;
        coin3.country = "UK";
        coin3.metal = "Nickel";
        coin3.weight = 5.0;
        coin3.yearOfMint = 1985;
        coin3.isRare = false;
        coin3.denomination = "50 Pence";
        System.out.println("Coin ID: " + coin3.coinId);
        System.out.println("Country: " + coin3.country);
        System.out.println("Metal: " + coin3.metal);
        System.out.println("Weight: " + coin3.weight + "g");
        System.out.println("Year of Mint: " + coin3.yearOfMint);
        System.out.println("Is Rare: " + coin3.isRare);
        System.out.println("Denomination: " + coin3.denomination);

        Coins coin4 = new Coins();
        coin4.coinId = 4;
        coin4.country = "Germany";
        coin4.metal = "Aluminium";
        coin4.weight = 2.1;
        coin4.yearOfMint = 1942;
        coin4.isRare = true;
        coin4.denomination = "5 Pfennig";
        System.out.println("Coin ID: " + coin4.coinId);
        System.out.println("Country: " + coin4.country);
        System.out.println("Metal: " + coin4.metal);
        System.out.println("Weight: " + coin4.weight + "g");
        System.out.println("Year of Mint: " + coin4.yearOfMint);
        System.out.println("Is Rare: " + coin4.isRare);
        System.out.println("Denomination: " + coin4.denomination);

        Coins coin5 = new Coins();
        coin5.coinId = 5;
        coin5.country = "India";
        coin5.metal = "Brass";
        coin5.weight = 4.3;
        coin5.yearOfMint = 2010;
        coin5.isRare = false;
        coin5.denomination = "2 Rupees";
        System.out.println("Coin ID: " + coin5.coinId);
        System.out.println("Country: " + coin5.country);
        System.out.println("Metal: " + coin5.metal);
        System.out.println("Weight: " + coin5.weight + "g");
        System.out.println("Year of Mint: " + coin5.yearOfMint);
        System.out.println("Is Rare: " + coin5.isRare);
        System.out.println("Denomination: " + coin5.denomination);

        Coins coin6 = new Coins();
        coin6.coinId = 6;
        coin6.country = "Japan";
        coin6.metal = "Zinc";
        coin6.weight = 3.1;
        coin6.yearOfMint = 1999;
        coin6.isRare = false;
        coin6.denomination = "10 Yen";
        System.out.println("Coin ID: " + coin6.coinId);
        System.out.println("Country: " + coin6.country);
        System.out.println("Metal: " + coin6.metal);
        System.out.println("Weight: " + coin6.weight + "g");
        System.out.println("Year of Mint: " + coin6.yearOfMint);
        System.out.println("Is Rare: " + coin6.isRare);
        System.out.println("Denomination: " + coin6.denomination);

        Coins coin7 = new Coins();
        coin7.coinId = 7;
        coin7.country = "France";
        coin7.metal = "Bronze";
        coin7.weight = 4.0;
        coin7.yearOfMint = 1920;
        coin7.isRare = true;
        coin7.denomination = "1 Franc";
        System.out.println("Coin ID: " + coin7.coinId);
        System.out.println("Country: " + coin7.country);
        System.out.println("Metal: " + coin7.metal);
        System.out.println("Weight: " + coin7.weight + "g");
        System.out.println("Year of Mint: " + coin7.yearOfMint);
        System.out.println("Is Rare: " + coin7.isRare);
        System.out.println("Denomination: " + coin7.denomination);

        Coins coin8 = new Coins();
        coin8.coinId = 8;
        coin8.country = "Canada";
        coin8.metal = "Steel";
        coin8.weight = 5.4;
        coin8.yearOfMint = 2005;
        coin8.isRare = false;
        coin8.denomination = "5 Cents";
        System.out.println("Coin ID: " + coin8.coinId);
        System.out.println("Country: " + coin8.country);
        System.out.println("Metal: " + coin8.metal);
        System.out.println("Weight: " + coin8.weight + "g");
        System.out.println("Year of Mint: " + coin8.yearOfMint);
        System.out.println("Is Rare: " + coin8.isRare);
        System.out.println("Denomination: " + coin8.denomination);

        Coins coin9 = new Coins();
        coin9.coinId = 9;
        coin9.country = "Italy";
        coin9.metal = "Silver";
        coin9.weight = 7.2;
        coin9.yearOfMint = 1900;
        coin9.isRare = true;
        coin9.denomination = "2 Lire";
        System.out.println("Coin ID: " + coin9.coinId);
        System.out.println("Country: " + coin9.country);
        System.out.println("Metal: " + coin9.metal);
        System.out.println("Weight: " + coin9.weight + "g");
        System.out.println("Year of Mint: " + coin9.yearOfMint);
        System.out.println("Is Rare: " + coin9.isRare);
        System.out.println("Denomination: " + coin9.denomination);

        Coins coin10 = new Coins();
        coin10.coinId = 10;
        coin10.country = "Russia";
        coin10.metal = "Copper";
        coin10.weight = 6.0;
        coin10.yearOfMint = 1991;
        coin10.isRare = false;
        coin10.denomination = "1 Rouble";
        System.out.println("Coin ID: " + coin10.coinId);
        System.out.println("Country: " + coin10.country);
        System.out.println("Metal: " + coin10.metal);
        System.out.println("Weight: " + coin10.weight + "g");
        System.out.println("Year of Mint: " + coin10.yearOfMint);
        System.out.println("Is Rare: " + coin10.isRare);
        System.out.println("Denomination: " + coin10.denomination);

               Coins coin11 = new Coins();
        coin11.coinId = 11;
        coin11.country = "China";
        coin11.metal = "Aluminium";
        coin11.weight = 3.2;
        coin11.yearOfMint = 1980;
        coin11.isRare = false;
        coin11.denomination = "1 Yuan";
        System.out.println("Coin ID: " + coin11.coinId);
        System.out.println("Country: " + coin11.country);
        System.out.println("Metal: " + coin11.metal);
        System.out.println("Weight: " + coin11.weight + "g");
        System.out.println("Year of Mint: " + coin11.yearOfMint);
        System.out.println("Is Rare: " + coin11.isRare);
        System.out.println("Denomination: " + coin11.denomination);

        Coins coin12 = new Coins();
        coin12.coinId = 12;
        coin12.country = "Brazil";
        coin12.metal = "Bronze";
        coin12.weight = 4.9;
        coin12.yearOfMint = 1975;
        coin12.isRare = true;
        coin12.denomination = "50 Centavos";
        System.out.println("Coin ID: " + coin12.coinId);
        System.out.println("Country: " + coin12.country);
        System.out.println("Metal: " + coin12.metal);
        System.out.println("Weight: " + coin12.weight + "g");
        System.out.println("Year of Mint: " + coin12.yearOfMint);
        System.out.println("Is Rare: " + coin12.isRare);
        System.out.println("Denomination: " + coin12.denomination);

        Coins coin13 = new Coins();
        coin13.coinId = 13;
        coin13.country = "Mexico";
        coin13.metal = "Silver";
        coin13.weight = 7.0;
        coin13.yearOfMint = 1990;
        coin13.isRare = false;
        coin13.denomination = "1 Peso";
        System.out.println("Coin ID: " + coin13.coinId);
        System.out.println("Country: " + coin13.country);
        System.out.println("Metal: " + coin13.metal);
        System.out.println("Weight: " + coin13.weight + "g");
        System.out.println("Year of Mint: " + coin13.yearOfMint);
        System.out.println("Is Rare: " + coin13.isRare);
        System.out.println("Denomination: " + coin13.denomination);

        Coins coin14 = new Coins();
        coin14.coinId = 14;
        coin14.country = "Spain";
        coin14.metal = "Copper";
        coin14.weight = 5.5;
        coin14.yearOfMint = 1966;
        coin14.isRare = true;
        coin14.denomination = "5 Pesetas";
        System.out.println("Coin ID: " + coin14.coinId);
        System.out.println("Country: " + coin14.country);
        System.out.println("Metal: " + coin14.metal);
        System.out.println("Weight: " + coin14.weight + "g");
        System.out.println("Year of Mint: " + coin14.yearOfMint);
        System.out.println("Is Rare: " + coin14.isRare);
        System.out.println("Denomination: " + coin14.denomination);

        Coins coin15 = new Coins();
        coin15.coinId = 15;
        coin15.country = "Australia";
        coin15.metal = "Nickel";
        coin15.weight = 6.1;
        coin15.yearOfMint = 2003;
        coin15.isRare = false;
        coin15.denomination = "10 Cents";
        System.out.println("Coin ID: " + coin15.coinId);
        System.out.println("Country: " + coin15.country);
        System.out.println("Metal: " + coin15.metal);
        System.out.println("Weight: " + coin15.weight + "g");
        System.out.println("Year of Mint: " + coin15.yearOfMint);
        System.out.println("Is Rare: " + coin15.isRare);
        System.out.println("Denomination: " + coin15.denomination);

        Coins coin16 = new Coins();
        coin16.coinId = 16;
        coin16.country = "Switzerland";
        coin16.metal = "Silver";
        coin16.weight = 7.3;
        coin16.yearOfMint = 1935;
        coin16.isRare = true;
        coin16.denomination = "2 Francs";
        System.out.println("Coin ID: " + coin16.coinId);
        System.out.println("Country: " + coin16.country);
        System.out.println("Metal: " + coin16.metal);
        System.out.println("Weight: " + coin16.weight + "g");
        System.out.println("Year of Mint: " + coin16.yearOfMint);
        System.out.println("Is Rare: " + coin16.isRare);
        System.out.println("Denomination: " + coin16.denomination);

        Coins coin17 = new Coins();
        coin17.coinId = 17;
        coin17.country = "South Africa";
        coin17.metal = "Brass";
        coin17.weight = 4.0;
        coin17.yearOfMint = 2011;
        coin17.isRare = false;
        coin17.denomination = "2 Rand";
        System.out.println("Coin ID: " + coin17.coinId);
        System.out.println("Country: " + coin17.country);
        System.out.println("Metal: " + coin17.metal);
        System.out.println("Weight: " + coin17.weight + "g");
        System.out.println("Year of Mint: " + coin17.yearOfMint);
        System.out.println("Is Rare: " + coin17.isRare);
        System.out.println("Denomination: " + coin17.denomination);

        Coins coin18 = new Coins();
        coin18.coinId = 18;
        coin18.country = "South Korea";
        coin18.metal = "Zinc";
        coin18.weight = 3.6;
        coin18.yearOfMint = 2000;
        coin18.isRare = false;
        coin18.denomination = "100 Won";
        System.out.println("Coin ID: " + coin18.coinId);
        System.out.println("Country: " + coin18.country);
        System.out.println("Metal: " + coin18.metal);
        System.out.println("Weight: " + coin18.weight + "g");
        System.out.println("Year of Mint: " + coin18.yearOfMint);
        System.out.println("Is Rare: " + coin18.isRare);
        System.out.println("Denomination: " + coin18.denomination);

        Coins coin19 = new Coins();
        coin19.coinId = 19;
        coin19.country = "New Zealand";
        coin19.metal = "Aluminium";
        coin19.weight = 2.9;
        coin19.yearOfMint = 1995;
        coin19.isRare = false;
        coin19.denomination = "20 Cents";
        System.out.println("Coin ID: " + coin19.coinId);
        System.out.println("Country: " + coin19.country);
        System.out.println("Metal: " + coin19.metal);
        System.out.println("Weight: " + coin19.weight + "g");
        System.out.println("Year of Mint: " + coin19.yearOfMint);
        System.out.println("Is Rare: " + coin19.isRare);
        System.out.println("Denomination: " + coin19.denomination);

        Coins coin20 = new Coins();
        coin20.coinId = 20;
        coin20.country = "Argentina";
        coin20.metal = "Nickel";
        coin20.weight = 5.7;
        coin20.yearOfMint = 1988;
        coin20.isRare = true;
        coin20.denomination = "1 Peso";
        System.out.println("Coin ID: " + coin20.coinId);
        System.out.println("Country: " + coin20.country);
        System.out.println("Metal: " + coin20.metal);
        System.out.println("Weight: " + coin20.weight + "g");
        System.out.println("Year of Mint: " + coin20.yearOfMint);
        System.out.println("Is Rare: " + coin20.isRare);
        System.out.println("Denomination: " + coin20.denomination);

        System.out.println("THE MAIN ENDED");
    }
}
