class GymEquipmentRunner {

    public static void main(String[] args) {

        System.out.println("THE MAIN STARTED");

        GymEquipment equip1 = new GymEquipment();
        equip1.equipmentId = 1;
        equip1.name = "Dumbbell";
        equip1.weight = 10.5;
        equip1.material = "Iron";
        equip1.isAdjustable = false;
        equip1.category = "Strength";
        equip1.brand = "FitPro";
        System.out.println("Equipment ID: " + equip1.equipmentId);
        System.out.println("Name: " + equip1.name);
        System.out.println("Weight: " + equip1.weight + " kg");
        System.out.println("Material: " + equip1.material);
        System.out.println("Adjustable: " + equip1.isAdjustable);
        System.out.println("Category: " + equip1.category);
        System.out.println("Brand: " + equip1.brand);

        GymEquipment equip2 = new GymEquipment();
        equip2.equipmentId = 2;
        equip2.name = "Barbell";
        equip2.weight = 20.0;
        equip2.material = "Steel";
        equip2.isAdjustable = true;
        equip2.category = "Strength";
        equip2.brand = "StrongMax";
        System.out.println("Equipment ID: " + equip2.equipmentId);
        System.out.println("Name: " + equip2.name);
        System.out.println("Weight: " + equip2.weight + " kg");
        System.out.println("Material: " + equip2.material);
        System.out.println("Adjustable: " + equip2.isAdjustable);
        System.out.println("Category: " + equip2.category);
        System.out.println("Brand: " + equip2.brand);

        GymEquipment equip3 = new GymEquipment();
        equip3.equipmentId = 3;
        equip3.name = "Treadmill";
        equip3.weight = 75.0;
        equip3.material = "Steel";
        equip3.isAdjustable = true;
        equip3.category = "Cardio";
        equip3.brand = "RunWay";
        System.out.println("Equipment ID: " + equip3.equipmentId);
        System.out.println("Name: " + equip3.name);
        System.out.println("Weight: " + equip3.weight + " kg");
        System.out.println("Material: " + equip3.material);
        System.out.println("Adjustable: " + equip3.isAdjustable);
        System.out.println("Category: " + equip3.category);
        System.out.println("Brand: " + equip3.brand);

        GymEquipment equip4 = new GymEquipment();
        equip4.equipmentId = 4;
        equip4.name = "Exercise Bike";
        equip4.weight = 60.0;
        equip4.material = "Aluminum";
        equip4.isAdjustable = true;
        equip4.category = "Cardio";
        equip4.brand = "CycleFit";
        System.out.println("Equipment ID: " + equip4.equipmentId);
        System.out.println("Name: " + equip4.name);
        System.out.println("Weight: " + equip4.weight + " kg");
        System.out.println("Material: " + equip4.material);
        System.out.println("Adjustable: " + equip4.isAdjustable);
        System.out.println("Category: " + equip4.category);
        System.out.println("Brand: " + equip4.brand);

        GymEquipment equip5 = new GymEquipment();
        equip5.equipmentId = 5;
        equip5.name = "Rowing Machine";
        equip5.weight = 55.5;
        equip5.material = "Steel";
        equip5.isAdjustable = true;
        equip5.category = "Cardio";
        equip5.brand = "RowMaster";
        System.out.println("Equipment ID: " + equip5.equipmentId);
        System.out.println("Name: " + equip5.name);
        System.out.println("Weight: " + equip5.weight + " kg");
        System.out.println("Material: " + equip5.material);
        System.out.println("Adjustable: " + equip5.isAdjustable);
        System.out.println("Category: " + equip5.category);
        System.out.println("Brand: " + equip5.brand);

        GymEquipment equip6 = new GymEquipment();
        equip6.equipmentId = 6;
        equip6.name = "Leg Press Machine";
        equip6.weight = 80.0;
        equip6.material = "Iron";
        equip6.isAdjustable = false;
        equip6.category = "Strength";
        equip6.brand = "LegBuild";
        System.out.println("Equipment ID: " + equip6.equipmentId);
        System.out.println("Name: " + equip6.name);
        System.out.println("Weight: " + equip6.weight + " kg");
        System.out.println("Material: " + equip6.material);
        System.out.println("Adjustable: " + equip6.isAdjustable);
        System.out.println("Category: " + equip6.category);
        System.out.println("Brand: " + equip6.brand);

        GymEquipment equip7 = new GymEquipment();
        equip7.equipmentId = 7;
        equip7.name = "Chest Press Machine";
        equip7.weight = 85.0;
        equip7.material = "Steel";
        equip7.isAdjustable = true;
        equip7.category = "Strength";
        equip7.brand = "ChestCore";
        System.out.println("Equipment ID: " + equip7.equipmentId);
        System.out.println("Name: " + equip7.name);
        System.out.println("Weight: " + equip7.weight + " kg");
        System.out.println("Material: " + equip7.material);
        System.out.println("Adjustable: " + equip7.isAdjustable);
        System.out.println("Category: " + equip7.category);
        System.out.println("Brand: " + equip7.brand);

        GymEquipment equip8 = new GymEquipment();
        equip8.equipmentId = 8;
        equip8.name = "Kettlebell";
        equip8.weight = 12.0;
        equip8.material = "Cast Iron";
        equip8.isAdjustable = false;
        equip8.category = "Strength";
        equip8.brand = "PowerBell";
        System.out.println("Equipment ID: " + equip8.equipmentId);
        System.out.println("Name: " + equip8.name);
        System.out.println("Weight: " + equip8.weight + " kg");
        System.out.println("Material: " + equip8.material);
        System.out.println("Adjustable: " + equip8.isAdjustable);
        System.out.println("Category: " + equip8.category);
        System.out.println("Brand: " + equip8.brand);

        GymEquipment equip9 = new GymEquipment();
        equip9.equipmentId = 9;
        equip9.name = "Pull-up Bar";
        equip9.weight = 7.5;
        equip9.material = "Steel";
        equip9.isAdjustable = false;
        equip9.category = "Bodyweight";
        equip9.brand = "FlexBar";
        System.out.println("Equipment ID: " + equip9.equipmentId);
        System.out.println("Name: " + equip9.name);
        System.out.println("Weight: " + equip9.weight + " kg");
        System.out.println("Material: " + equip9.material);
        System.out.println("Adjustable: " + equip9.isAdjustable);
        System.out.println("Category: " + equip9.category);
        System.out.println("Brand: " + equip9.brand);

        GymEquipment equip10 = new GymEquipment();
        equip10.equipmentId = 10;
        equip10.name = "Resistance Bands";
        equip10.weight = 0.8;
        equip10.material = "Rubber";
        equip10.isAdjustable = true;
        equip10.category = "Flexibility";
        equip10.brand = "StretchX";
        System.out.println("Equipment ID: " + equip10.equipmentId);
        System.out.println("Name: " + equip10.name);
        System.out.println("Weight: " + equip10.weight + " kg");
        System.out.println("Material: " + equip10.material);
        System.out.println("Adjustable: " + equip10.isAdjustable);
        System.out.println("Category: " + equip10.category);
        System.out.println("Brand: " + equip10.brand);


        GymEquipment equip11 = new GymEquipment();
        equip11.equipmentId = 11;
        equip11.name = "Jump Rope";
        equip11.weight = 0.4;
        equip11.material = "Plastic";
        equip11.isAdjustable = true;
        equip11.category = "Cardio";
        equip11.brand = "SpeedRope";
        System.out.println("Equipment ID: " + equip11.equipmentId);
        System.out.println("Name: " + equip11.name);
        System.out.println("Weight: " + equip11.weight + " kg");
        System.out.println("Material: " + equip11.material);
        System.out.println("Adjustable: " + equip11.isAdjustable);
        System.out.println("Category: " + equip11.category);
        System.out.println("Brand: " + equip11.brand);

        GymEquipment equip12 = new GymEquipment();
        equip12.equipmentId = 12;
        equip12.name = "Treadmill Desk";
        equip12.weight = 100.0;
        equip12.material = "Steel & Plastic";
        equip12.isAdjustable = true;
        equip12.category = "Cardio";
        equip12.brand = "WalkNWork";
        System.out.println("Equipment ID: " + equip12.equipmentId);
        System.out.println("Name: " + equip12.name);
        System.out.println("Weight: " + equip12.weight + " kg");
        System.out.println("Material: " + equip12.material);
        System.out.println("Adjustable: " + equip12.isAdjustable);
        System.out.println("Category: " + equip12.category);
        System.out.println("Brand: " + equip12.brand);

        GymEquipment equip13 = new GymEquipment();
        equip13.equipmentId = 13;
        equip13.name = "Incline Bench";
        equip13.weight = 28.0;
        equip13.material = "Iron";
        equip13.isAdjustable = true;
        equip13.category = "Strength";
        equip13.brand = "BenchPro";
        System.out.println("Equipment ID: " + equip13.equipmentId);
        System.out.println("Name: " + equip13.name);
        System.out.println("Weight: " + equip13.weight + " kg");
        System.out.println("Material: " + equip13.material);
        System.out.println("Adjustable: " + equip13.isAdjustable);
        System.out.println("Category: " + equip13.category);
        System.out.println("Brand: " + equip13.brand);

        GymEquipment equip14 = new GymEquipment();
        equip14.equipmentId = 14;
        equip14.name = "Cable Crossover";
        equip14.weight = 150.0;
        equip14.material = "Steel";
        equip14.isAdjustable = true;
        equip14.category = "Strength";
        equip14.brand = "CableKing";
        System.out.println("Equipment ID: " + equip14.equipmentId);
        System.out.println("Name: " + equip14.name);
        System.out.println("Weight: " + equip14.weight + " kg");
        System.out.println("Material: " + equip14.material);
        System.out.println("Adjustable: " + equip14.isAdjustable);
        System.out.println("Category: " + equip14.category);
        System.out.println("Brand: " + equip14.brand);

        GymEquipment equip15 = new GymEquipment();
        equip15.equipmentId = 15;
        equip15.name = "Medicine Ball";
        equip15.weight = 6.0;
        equip15.material = "Rubber";
        equip15.isAdjustable = false;
        equip15.category = "Functional";
        equip15.brand = "BallFit";
        System.out.println("Equipment ID: " + equip15.equipmentId);
        System.out.println("Name: " + equip15.name);
        System.out.println("Weight: " + equip15.weight + " kg");
        System.out.println("Material: " + equip15.material);
        System.out.println("Adjustable: " + equip15.isAdjustable);
        System.out.println("Category: " + equip15.category);
        System.out.println("Brand: " + equip15.brand);

        GymEquipment equip16 = new GymEquipment();
        equip16.equipmentId = 16;
        equip16.name = "Foam Roller";
        equip16.weight = 1.0;
        equip16.material = "Foam";
        equip16.isAdjustable = false;
        equip16.category = "Recovery";
        equip16.brand = "RollEase";
        System.out.println("Equipment ID: " + equip16.equipmentId);
        System.out.println("Name: " + equip16.name);
        System.out.println("Weight: " + equip16.weight + " kg");
        System.out.println("Material: " + equip16.material);
        System.out.println("Adjustable: " + equip16.isAdjustable);
        System.out.println("Category: " + equip16.category);
        System.out.println("Brand: " + equip16.brand);

        GymEquipment equip17 = new GymEquipment();
        equip17.equipmentId = 17;
        equip17.name = "Stepper";
        equip17.weight = 18.5;
        equip17.material = "Plastic & Steel";
        equip17.isAdjustable = true;
        equip17.category = "Cardio";
        equip17.brand = "StepUp";
        System.out.println("Equipment ID: " + equip17.equipmentId);
        System.out.println("Name: " + equip17.name);
        System.out.println("Weight: " + equip17.weight + " kg");
        System.out.println("Material: " + equip17.material);
        System.out.println("Adjustable: " + equip17.isAdjustable);
        System.out.println("Category: " + equip17.category);
        System.out.println("Brand: " + equip17.brand);

        GymEquipment equip18 = new GymEquipment();
        equip18.equipmentId = 18;
        equip18.name = "Tricep Bar";
        equip18.weight = 8.0;
        equip18.material = "Steel";
        equip18.isAdjustable = false;
        equip18.category = "Strength";
        equip18.brand = "ArmIron";
        System.out.println("Equipment ID: " + equip18.equipmentId);
        System.out.println("Name: " + equip18.name);
        System.out.println("Weight: " + equip18.weight + " kg");
        System.out.println("Material: " + equip18.material);
        System.out.println("Adjustable: " + equip18.isAdjustable);
        System.out.println("Category: " + equip18.category);
        System.out.println("Brand: " + equip18.brand);

        GymEquipment equip19 = new GymEquipment();
        equip19.equipmentId = 19;
        equip19.name = "Battle Ropes";
        equip19.weight = 15.0;
        equip19.material = "Nylon";
        equip19.isAdjustable = false;
        equip19.category = "Conditioning";
        equip19.brand = "RopeX";
        System.out.println("Equipment ID: " + equip19.equipmentId);
        System.out.println("Name: " + equip19.name);
        System.out.println("Weight: " + equip19.weight + " kg");
        System.out.println("Material: " + equip19.material);
        System.out.println("Adjustable: " + equip19.isAdjustable);
        System.out.println("Category: " + equip19.category);
        System.out.println("Brand: " + equip19.brand);

        GymEquipment equip20 = new GymEquipment();
        equip20.equipmentId = 20;
        equip20.name = "Ab Roller";
        equip20.weight = 2.0;
        equip20.material = "Plastic & Rubber";
        equip20.isAdjustable = false;
        equip20.category = "Core";
        equip20.brand = "AbPower";
        System.out.println("Equipment ID: " + equip20.equipmentId);
        System.out.println("Name: " + equip20.name);
        System.out.println("Weight: " + equip20.weight + " kg");
        System.out.println("Material: " + equip20.material);
        System.out.println("Adjustable: " + equip20.isAdjustable);
        System.out.println("Category: " + equip20.category);
        System.out.println("Brand: " + equip20.brand);

        System.out.println("THE MAIN ENDED");
    }
}


       
