class HairClipRunner {

    public static void main(String[] args) {

        System.out.println("THE MAIN STARTED");

        HairClip clip1 = new HairClip();
        clip1.clipId = 1;
        clip1.brand = "Clippy";
        clip1.material = "Plastic";
        clip1.color = "Red";
        clip1.lengthInCm = 5.5;
        clip1.isDecorated = true;
        clip1.clipType = "Alligator";
        System.out.println("Clip ID: " + clip1.clipId);
        System.out.println("Brand: " + clip1.brand);
        System.out.println("Material: " + clip1.material);
        System.out.println("Color: " + clip1.color);
        System.out.println("Length: " + clip1.lengthInCm + " cm");
        System.out.println("Decorated: " + clip1.isDecorated);
        System.out.println("Type: " + clip1.clipType);

        HairClip clip2 = new HairClip();
        clip2.clipId = 2;
        clip2.brand = "Snappy";
        clip2.material = "Metal";
        clip2.color = "Black";
        clip2.lengthInCm = 6.0;
        clip2.isDecorated = false;
        clip2.clipType = "Snap Clip";
        System.out.println("Clip ID: " + clip2.clipId);
        System.out.println("Brand: " + clip2.brand);
        System.out.println("Material: " + clip2.material);
        System.out.println("Color: " + clip2.color);
        System.out.println("Length: " + clip2.lengthInCm + " cm");
        System.out.println("Decorated: " + clip2.isDecorated);
        System.out.println("Type: " + clip2.clipType);

        HairClip clip3 = new HairClip();
        clip3.clipId = 3;
        clip3.brand = "FancyLocks";
        clip3.material = "Wood";
        clip3.color = "Brown";
        clip3.lengthInCm = 5.8;
        clip3.isDecorated = true;
        clip3.clipType = "Comb Clip";
        System.out.println("Clip ID: " + clip3.clipId);
        System.out.println("Brand: " + clip3.brand);
        System.out.println("Material: " + clip3.material);
        System.out.println("Color: " + clip3.color);
        System.out.println("Length: " + clip3.lengthInCm + " cm");
        System.out.println("Decorated: " + clip3.isDecorated);
        System.out.println("Type: " + clip3.clipType);

        HairClip clip4 = new HairClip();
        clip4.clipId = 4;
        clip4.brand = "GlamFix";
        clip4.material = "Plastic";
        clip4.color = "Pink";
        clip4.lengthInCm = 4.5;
        clip4.isDecorated = false;
        clip4.clipType = "Banana Clip";
        System.out.println("Clip ID: " + clip4.clipId);
        System.out.println("Brand: " + clip4.brand);
        System.out.println("Material: " + clip4.material);
        System.out.println("Color: " + clip4.color);
        System.out.println("Length: " + clip4.lengthInCm + " cm");
        System.out.println("Decorated: " + clip4.isDecorated);
        System.out.println("Type: " + clip4.clipType);

        HairClip clip5 = new HairClip();
        clip5.clipId = 5;
        clip5.brand = "ClipArt";
        clip5.material = "Metal";
        clip5.color = "Silver";
        clip5.lengthInCm = 6.2;
        clip5.isDecorated = false;
        clip5.clipType = "Snap Clip";
        System.out.println("Clip ID: " + clip5.clipId);
        System.out.println("Brand: " + clip5.brand);
        System.out.println("Material: " + clip5.material);
        System.out.println("Color: " + clip5.color);
        System.out.println("Length: " + clip5.lengthInCm + " cm");
        System.out.println("Decorated: " + clip5.isDecorated);
        System.out.println("Type: " + clip5.clipType);

        HairClip clip6 = new HairClip();
        clip6.clipId = 6;
        clip6.brand = "StyleSnap";
        clip6.material = "Plastic";
        clip6.color = "Blue";
        clip6.lengthInCm = 5.0;
        clip6.isDecorated = true;
        clip6.clipType = "Claw Clip";
        System.out.println("Clip ID: " + clip6.clipId);
        System.out.println("Brand: " + clip6.brand);
        System.out.println("Material: " + clip6.material);
        System.out.println("Color: " + clip6.color);
        System.out.println("Length: " + clip6.lengthInCm + " cm");
        System.out.println("Decorated: " + clip6.isDecorated);
        System.out.println("Type: " + clip6.clipType);

        HairClip clip7 = new HairClip();
        clip7.clipId = 7;
        clip7.brand = "CuteGrip";
        clip7.material = "Rubber";
        clip7.color = "Yellow";
        clip7.lengthInCm = 4.0;
        clip7.isDecorated = true;
        clip7.clipType = "Mini Clip";
        System.out.println("Clip ID: " + clip7.clipId);
        System.out.println("Brand: " + clip7.brand);
        System.out.println("Material: " + clip7.material);
        System.out.println("Color: " + clip7.color);
        System.out.println("Length: " + clip7.lengthInCm + " cm");
        System.out.println("Decorated: " + clip7.isDecorated);
        System.out.println("Type: " + clip7.clipType);

        HairClip clip8 = new HairClip();
        clip8.clipId = 8;
        clip8.brand = "HairBee";
        clip8.material = "Plastic";
        clip8.color = "White";
        clip8.lengthInCm = 5.2;
        clip8.isDecorated = false;
        clip8.clipType = "Barrette";
        System.out.println("Clip ID: " + clip8.clipId);
        System.out.println("Brand: " + clip8.brand);
        System.out.println("Material: " + clip8.material);
        System.out.println("Color: " + clip8.color);
        System.out.println("Length: " + clip8.lengthInCm + " cm");
        System.out.println("Decorated: " + clip8.isDecorated);
        System.out.println("Type: " + clip8.clipType);

        HairClip clip9 = new HairClip();
        clip9.clipId = 9;
        clip9.brand = "TressHold";
        clip9.material = "Metal";
        clip9.color = "Gold";
        clip9.lengthInCm = 6.5;
        clip9.isDecorated = true;
        clip9.clipType = "Duckbill";
        System.out.println("Clip ID: " + clip9.clipId);
        System.out.println("Brand: " + clip9.brand);
        System.out.println("Material: " + clip9.material);
        System.out.println("Color: " + clip9.color);
        System.out.println("Length: " + clip9.lengthInCm + " cm");
        System.out.println("Decorated: " + clip9.isDecorated);
        System.out.println("Type: " + clip9.clipType);

        HairClip clip10 = new HairClip();
        clip10.clipId = 10;
        clip10.brand = "FixMyHair";
        clip10.material = "Plastic";
        clip10.color = "Green";
        clip10.lengthInCm = 4.9;
        clip10.isDecorated = false;
        clip10.clipType = "Sectioning Clip";
        System.out.println("Clip ID: " + clip10.clipId);
        System.out.println("Brand: " + clip10.brand);
        System.out.println("Material: " + clip10.material);
        System.out.println("Color: " + clip10.color);
        System.out.println("Length: " + clip10.lengthInCm + " cm");
        System.out.println("Decorated: " + clip10.isDecorated);
        System.out.println("Type: " + clip10.clipType);

        HairClip clip11 = new HairClip();
        clip11.clipId = 11;
        clip11.brand = "Hairstylo";
        clip11.material = "Wood";
        clip11.color = "Beige";
        clip11.lengthInCm = 5.3;
        clip11.isDecorated = true;
        clip11.clipType = "U-Clip";
        System.out.println("Clip ID: " + clip11.clipId);
        System.out.println("Brand: " + clip11.brand);
        System.out.println("Material: " + clip11.material);
        System.out.println("Color: " + clip11.color);
        System.out.println("Length: " + clip11.lengthInCm + " cm");
        System.out.println("Decorated: " + clip11.isDecorated);
        System.out.println("Type: " + clip11.clipType);

        HairClip clip12 = new HairClip();
        clip12.clipId = 12;
        clip12.brand = "PearlClip";
        clip12.material = "Plastic";
        clip12.color = "Purple";
        clip12.lengthInCm = 4.7;
        clip12.isDecorated = true;
        clip12.clipType = "Bobby Pin";
        System.out.println("Clip ID: " + clip12.clipId);
        System.out.println("Brand: " + clip12.brand);
        System.out.println("Material: " + clip12.material);
        System.out.println("Color: " + clip12.color);
        System.out.println("Length: " + clip12.lengthInCm + " cm");
        System.out.println("Decorated: " + clip12.isDecorated);
        System.out.println("Type: " + clip12.clipType);
        
        HairClip clip13 = new HairClip();
        clip13.clipId = 13;
        clip13.brand = "ButterflyCharm";
        clip13.material = "Plastic";
        clip13.color = "Peach";
        clip13.lengthInCm = 5.1;
        clip13.isDecorated = true;
        clip13.clipType = "Butterfly Clip";
        System.out.println("Clip ID: " + clip13.clipId);
        System.out.println("Brand: " + clip13.brand);
        System.out.println("Material: " + clip13.material);
        System.out.println("Color: " + clip13.color);
        System.out.println("Length: " + clip13.lengthInCm + " cm");
        System.out.println("Decorated: " + clip13.isDecorated);
        System.out.println("Type: " + clip13.clipType);

        HairClip clip14 = new HairClip();
        clip14.clipId = 14;
        clip14.brand = "ClipEase";
        clip14.material = "Metal";
        clip14.color = "Copper";
        clip14.lengthInCm = 6.4;
        clip14.isDecorated = false;
        clip14.clipType = "Alligator Clip";
        System.out.println("Clip ID: " + clip14.clipId);
        System.out.println("Brand: " + clip14.brand);
        System.out.println("Material: " + clip14.material);
        System.out.println("Color: " + clip14.color);
        System.out.println("Length: " + clip14.lengthInCm + " cm");
        System.out.println("Decorated: " + clip14.isDecorated);
        System.out.println("Type: " + clip14.clipType);

        HairClip clip15 = new HairClip();
        clip15.clipId = 15;
        clip15.brand = "HairTamer";
        clip15.material = "Plastic";
        clip15.color = "Lavender";
        clip15.lengthInCm = 4.2;
        clip15.isDecorated = true;
        clip15.clipType = "Wave Clip";
        System.out.println("Clip ID: " + clip15.clipId);
        System.out.println("Brand: " + clip15.brand);
        System.out.println("Material: " + clip15.material);
        System.out.println("Color: " + clip15.color);
        System.out.println("Length: " + clip15.lengthInCm + " cm");
        System.out.println("Decorated: " + clip15.isDecorated);
        System.out.println("Type: " + clip15.clipType);

        HairClip clip16 = new HairClip();
        clip16.clipId = 16;
        clip16.brand = "GoldenLocks";
        clip16.material = "Metal";
        clip16.color = "Golden";
        clip16.lengthInCm = 6.0;
        clip16.isDecorated = true;
        clip16.clipType = "Designer Clip";
        System.out.println("Clip ID: " + clip16.clipId);
        System.out.println("Brand: " + clip16.brand);
        System.out.println("Material: " + clip16.material);
        System.out.println("Color: " + clip16.color);
        System.out.println("Length: " + clip16.lengthInCm + " cm");
        System.out.println("Decorated: " + clip16.isDecorated);
        System.out.println("Type: " + clip16.clipType);

        HairClip clip17 = new HairClip();
        clip17.clipId = 17;
        clip17.brand = "ChicSnap";
        clip17.material = "Plastic";
        clip17.color = "Grey";
        clip17.lengthInCm = 5.5;
        clip17.isDecorated = false;
        clip17.clipType = "Flat Clip";
        System.out.println("Clip ID: " + clip17.clipId);
        System.out.println("Brand: " + clip17.brand);
        System.out.println("Material: " + clip17.material);
        System.out.println("Color: " + clip17.color);
        System.out.println("Length: " + clip17.lengthInCm + " cm");
        System.out.println("Decorated: " + clip17.isDecorated);
        System.out.println("Type: " + clip17.clipType);

        HairClip clip18 = new HairClip();
        clip18.clipId = 18;
        clip18.brand = "ElegantHold";
        clip18.material = "Wood";
        clip18.color = "Mahogany";
        clip18.lengthInCm = 5.6;
        clip18.isDecorated = true;
        clip18.clipType = "Fan Clip";
        System.out.println("Clip ID: " + clip18.clipId);
        System.out.println("Brand: " + clip18.brand);
        System.out.println("Material: " + clip18.material);
        System.out.println("Color: " + clip18.color);
        System.out.println("Length: " + clip18.lengthInCm + " cm");
        System.out.println("Decorated: " + clip18.isDecorated);
        System.out.println("Type: " + clip18.clipType);

        HairClip clip19 = new HairClip();
        clip19.clipId = 19;
        clip19.brand = "PixieClip";
        clip19.material = "Plastic";
        clip19.color = "Aqua";
        clip19.lengthInCm = 4.4;
        clip19.isDecorated = false;
        clip19.clipType = "Clamp Clip";
        System.out.println("Clip ID: " + clip19.clipId);
        System.out.println("Brand: " + clip19.brand);
        System.out.println("Material: " + clip19.material);
        System.out.println("Color: " + clip19.color);
        System.out.println("Length: " + clip19.lengthInCm + " cm");
        System.out.println("Decorated: " + clip19.isDecorated);
        System.out.println("Type: " + clip19.clipType);

        HairClip clip20 = new HairClip();
        clip20.clipId = 20;
        clip20.brand = "TwistNHold";
        clip20.material = "Metal";
        clip20.color = "Black";
        clip20.lengthInCm = 6.1;
        clip20.isDecorated = true;
        clip20.clipType = "Spiral Clip";
        System.out.println("Clip ID: " + clip20.clipId);
        System.out.println("Brand: " + clip20.brand);
        System.out.println("Material: " + clip20.material);
        System.out.println("Color: " + clip20.color);
        System.out.println("Length: " + clip20.lengthInCm + " cm");
        System.out.println("Decorated: " + clip20.isDecorated);
        System.out.println("Type: " + clip20.clipType);
}
}
