class HatRunner {

    public static void main(String[] args) {

        System.out.println("THE MAIN STARTED");

        Hat h1 = new Hat();
        h1.hatId = 1;
        h1.type = "Cap";
        h1.color = "Black";
        h1.material = "Cotton";
        h1.size = 58.0;
        h1.isAdjustable = true;
        h1.brand = "Nike";
        System.out.println("Hat ID: " + h1.hatId);
        System.out.println("Type: " + h1.type);
        System.out.println("Color: " + h1.color);
        System.out.println("Material: " + h1.material);
        System.out.println("Size: " + h1.size);
        System.out.println("Adjustable: " + h1.isAdjustable);
        System.out.println("Brand: " + h1.brand);
        System.out.println("---------------");

        Hat h2 = new Hat();
        h2.hatId = 2;
        h2.type = "Beanie";
        h2.color = "Grey";
        h2.material = "Wool";
        h2.size = 56.5;
        h2.isAdjustable = false;
        h2.brand = "Adidas";
        System.out.println("Hat ID: " + h2.hatId);
        System.out.println("Type: " + h2.type);
        System.out.println("Color: " + h2.color);
        System.out.println("Material: " + h2.material);
        System.out.println("Size: " + h2.size);
        System.out.println("Adjustable: " + h2.isAdjustable);
        System.out.println("Brand: " + h2.brand);
        System.out.println("---------------");

        Hat h3 = new Hat();
        h3.hatId = 3;
        h3.type = "Fedora";
        h3.color = "Brown";
        h3.material = "Felt";
        h3.size = 59.0;
        h3.isAdjustable = false;
        h3.brand = "Zara";
        System.out.println("Hat ID: " + h3.hatId);
        System.out.println("Type: " + h3.type);
        System.out.println("Color: " + h3.color);
        System.out.println("Material: " + h3.material);
        System.out.println("Size: " + h3.size);
        System.out.println("Adjustable: " + h3.isAdjustable);
        System.out.println("Brand: " + h3.brand);
        System.out.println("---------------");

        Hat h4 = new Hat();
        h4.hatId = 4;
        h4.type = "Snapback";
        h4.color = "Red";
        h4.material = "Polyester";
        h4.size = 60.0;
        h4.isAdjustable = true;
        h4.brand = "Puma";
        System.out.println("Hat ID: " + h4.hatId);
        System.out.println("Type: " + h4.type);
        System.out.println("Color: " + h4.color);
        System.out.println("Material: " + h4.material);
        System.out.println("Size: " + h4.size);
        System.out.println("Adjustable: " + h4.isAdjustable);
        System.out.println("Brand: " + h4.brand);
        System.out.println("---------------");

        Hat h5 = new Hat();
        h5.hatId = 5;
        h5.type = "Panama";
        h5.color = "White";
        h5.material = "Straw";
        h5.size = 57.0;
        h5.isAdjustable = false;
        h5.brand = "Uniqlo";
        System.out.println("Hat ID: " + h5.hatId);
        System.out.println("Type: " + h5.type);
        System.out.println("Color: " + h5.color);
        System.out.println("Material: " + h5.material);
        System.out.println("Size: " + h5.size);
        System.out.println("Adjustable: " + h5.isAdjustable);
        System.out.println("Brand: " + h5.brand);
        System.out.println("---------------");
 
                Hat h6 = new Hat();
        h6.hatId = 6;
        h6.type = "Cowboy";
        h6.color = "Tan";
        h6.material = "Leather";
        h6.size = 61.0;
        h6.isAdjustable = false;
        h6.brand = "Wrangler";
        System.out.println("Hat ID: " + h6.hatId);
        System.out.println("Type: " + h6.type);
        System.out.println("Color: " + h6.color);
        System.out.println("Material: " + h6.material);
        System.out.println("Size: " + h6.size);
        System.out.println("Adjustable: " + h6.isAdjustable);
        System.out.println("Brand: " + h6.brand);
        System.out.println("---------------");

        Hat h7 = new Hat();
        h7.hatId = 7;
        h7.type = "Top Hat";
        h7.color = "Black";
        h7.material = "Silk";
        h7.size = 60.5;
        h7.isAdjustable = false;
        h7.brand = "VintageWear";
        System.out.println("Hat ID: " + h7.hatId);
        System.out.println("Type: " + h7.type);
        System.out.println("Color: " + h7.color);
        System.out.println("Material: " + h7.material);
        System.out.println("Size: " + h7.size);
        System.out.println("Adjustable: " + h7.isAdjustable);
        System.out.println("Brand: " + h7.brand);
        System.out.println("---------------");

        Hat h8 = new Hat();
        h8.hatId = 8;
        h8.type = "Beret";
        h8.color = "Navy";
        h8.material = "Wool";
        h8.size = 55.0;
        h8.isAdjustable = false;
        h8.brand = "FrenchStyle";
        System.out.println("Hat ID: " + h8.hatId);
        System.out.println("Type: " + h8.type);
        System.out.println("Color: " + h8.color);
        System.out.println("Material: " + h8.material);
        System.out.println("Size: " + h8.size);
        System.out.println("Adjustable: " + h8.isAdjustable);
        System.out.println("Brand: " + h8.brand);
        System.out.println("---------------");

        Hat h9 = new Hat();
        h9.hatId = 9;
        h9.type = "Trilby";
        h9.color = "Grey";
        h9.material = "Wool Blend";
        h9.size = 58.5;
        h9.isAdjustable = false;
        h9.brand = "UrbanStyle";
        System.out.println("Hat ID: " + h9.hatId);
        System.out.println("Type: " + h9.type);
        System.out.println("Color: " + h9.color);
        System.out.println("Material: " + h9.material);
        System.out.println("Size: " + h9.size);
        System.out.println("Adjustable: " + h9.isAdjustable);
        System.out.println("Brand: " + h9.brand);
        System.out.println("---------------");

        Hat h10 = new Hat();
        h10.hatId = 10;
        h10.type = "Sun Hat";
        h10.color = "Beige";
        h10.material = "Straw";
        h10.size = 59.5;
        h10.isAdjustable = true;
        h10.brand = "BeachWear";
        System.out.println("Hat ID: " + h10.hatId);
        System.out.println("Type: " + h10.type);
        System.out.println("Color: " + h10.color);
        System.out.println("Material: " + h10.material);
        System.out.println("Size: " + h10.size);
        System.out.println("Adjustable: " + h10.isAdjustable);
        System.out.println("Brand: " + h10.brand);
        System.out.println("---------------");

        Hat h11 = new Hat();
        h11.hatId = 11;
        h11.type = "Boater";
        h11.color = "Cream";
        h11.material = "Straw";
        h11.size = 57.0;
        h11.isAdjustable = false;
        h11.brand = "RetroCo";
        System.out.println("Hat ID: " + h11.hatId);
        System.out.println("Type: " + h11.type);
        System.out.println("Color: " + h11.color);
        System.out.println("Material: " + h11.material);
        System.out.println("Size: " + h11.size);
        System.out.println("Adjustable: " + h11.isAdjustable);
        System.out.println("Brand: " + h11.brand);
        System.out.println("---------------");

        Hat h12 = new Hat();
        h12.hatId = 12;
        h12.type = "Bucket Hat";
        h12.color = "Olive";
        h12.material = "Canvas";
        h12.size = 58.0;
        h12.isAdjustable = true;
        h12.brand = "StreetWear";
        System.out.println("Hat ID: " + h12.hatId);
        System.out.println("Type: " + h12.type);
        System.out.println("Color: " + h12.color);
        System.out.println("Material: " + h12.material);
        System.out.println("Size: " + h12.size);
        System.out.println("Adjustable: " + h12.isAdjustable);
        System.out.println("Brand: " + h12.brand);
        System.out.println("---------------");

        Hat h13 = new Hat();
        h13.hatId = 13;
        h13.type = "Newsboy";
        h13.color = "Charcoal";
        h13.material = "Tweed";
        h13.size = 56.0;
        h13.isAdjustable = false;
        h13.brand = "Vintage";
        System.out.println("Hat ID: " + h13.hatId);
        System.out.println("Type: " + h13.type);
        System.out.println("Color: " + h13.color);
        System.out.println("Material: " + h13.material);
        System.out.println("Size: " + h13.size);
        System.out.println("Adjustable: " + h13.isAdjustable);
        System.out.println("Brand: " + h13.brand);
        System.out.println("---------------");

        Hat h14 = new Hat();
        h14.hatId = 14;
        h14.type = "Flat Cap";
        h14.color = "Olive";
        h14.material = "Cotton Blend";
        h14.size = 59.0;
        h14.isAdjustable = false;
        h14.brand = "ClassicWear";
        System.out.println("Hat ID: " + h14.hatId);
        System.out.println("Type: " + h14.type);
        System.out.println("Color: " + h14.color);
        System.out.println("Material: " + h14.material);
        System.out.println("Size: " + h14.size);
        System.out.println("Adjustable: " + h14.isAdjustable);
        System.out.println("Brand: " + h14.brand);
        System.out.println("---------------");

        Hat h15 = new Hat();
        h15.hatId = 15;
        h15.type = "Safari";
        h15.color = "Khaki";
        h15.material = "Cotton";
        h15.size = 60.0;
        h15.isAdjustable = true;
        h15.brand = "AdventureGear";
        System.out.println("Hat ID: " + h15.hatId);
        System.out.println("Type: " + h15.type);
        System.out.println("Color: " + h15.color);
        System.out.println("Material: " + h15.material);
        System.out.println("Size: " + h15.size);
        System.out.println("Adjustable: " + h15.isAdjustable);
        System.out.println("Brand: " + h15.brand);
        System.out.println("---------------");

        Hat h16 = new Hat();
        h16.hatId = 16;
        h16.type = "Visor";
        h16.color = "Blue";
        h16.material = "Polyester";
        h16.size = 58.5;
        h16.isAdjustable = true;
        h16.brand = "Sporty";
        System.out.println("Hat ID: " + h16.hatId);
        System.out.println("Type: " + h16.type);
        System.out.println("Color: " + h16.color);
        System.out.println("Material: " + h16.material);
        System.out.println("Size: " + h16.size);
        System.out.println("Adjustable: " + h16.isAdjustable);
        System.out.println("Brand: " + h16.brand);
        System.out.println("---------------");

        Hat h17 = new Hat();
        h17.hatId = 17;
        h17.type = "Turban";
        h17.color = "Maroon";
        h17.material = "Silk";
        h17.size = 61.5;
        h17.isAdjustable = false;
        h17.brand = "Traditional";
        System.out.println("Hat ID: " + h17.hatId);
        System.out.println("Type: " + h17.type);
        System.out.println("Color: " + h17.color);
        System.out.println("Material: " + h17.material);
        System.out.println("Size: " + h17.size);
        System.out.println("Adjustable: " + h17.isAdjustable);
        System.out.println("Brand: " + h17.brand);
        System.out.println("---------------");

        Hat h18 = new Hat();
        h18.hatId = 18;
        h18.type = "Hard Hat";
        h18.color = "Yellow";
        h18.material = "Plastic";
        h18.size = 62.0;
        h18.isAdjustable = true;
        h18.brand = "SafetyFirst";
        System.out.println("Hat ID: " + h18.hatId);
        System.out.println("Type: " + h18.type);
        System.out.println("Color: " + h18.color);
        System.out.println("Material: " + h18.material);
        System.out.println("Size: " + h18.size);
        System.out.println("Adjustable: " + h18.isAdjustable);
        System.out.println("Brand: " + h18.brand);
        System.out.println("---------------");

        Hat h19 = new Hat();
        h19.hatId = 19;
        h19.type = "Chef Hat";
        h19.color = "White";
        h19.material = "Cotton";
        h19.size = 63.0;
        h19.isAdjustable = true;
        h19.brand = "KitchenKing";
        System.out.println("Hat ID: " + h19.hatId);
        System.out.println("Type: " + h19.type);
        System.out.println("Color: " + h19.color);
        System.out.println("Material: " + h19.material);
        System.out.println("Size: " + h19.size);
        System.out.println("Adjustable: " + h19.isAdjustable);
        System.out.println("Brand: " + h19.brand);
        System.out.println("---------------");

        Hat h20 = new Hat();
        h20.hatId = 20;
        h20.type = "Santa Hat";
        h20.color = "Red & White";
        h20.material = "Fleece";
        h20.size = 60.5;
        h20.isAdjustable = true;
        h20.brand = "HolidayWear";
        System.out.println("Hat ID: " + h20.hatId);
        System.out.println("Type: " + h20.type);
        System.out.println("Color: " + h20.color);
        System.out.println("Material: " + h20.material);
        System.out.println("Size: " + h20.size);
        System.out.println("Adjustable: " + h20.isAdjustable);
        System.out.println("Brand: " + h20.brand);
        System.out.println("---------------");


        System.out.println("THE MAIN ENDED");
    }
}
