class InvitationCardRunner {
    public static void main(String[] args) {
        System.out.println("THE MAIN STARTED");

        InvitationCard i1 = new InvitationCard();
        i1.occasion = "Wedding";
        i1.hostName = "Ravi Kumar";
        i1.venue = "Leela Palace";
        i1.date = "12-11-2025";
        i1.time = "6:00 PM";
        i1.numberOfGuests = 300;
        i1.isRsvpRequired = true;
        System.out.println("Occasion: " + i1.occasion);
        System.out.println("Host Name: " + i1.hostName);
        System.out.println("Venue: " + i1.venue);
        System.out.println("Date: " + i1.date);
        System.out.println("Time: " + i1.time);
        System.out.println("Number of Guests: " + i1.numberOfGuests);
        System.out.println("RSVP Required: " + i1.isRsvpRequired);

        InvitationCard i2 = new InvitationCard();
        i2.occasion = "Birthday";
        i2.hostName = "Anjali Sharma";
        i2.venue = "Green Gardens";
        i2.date = "23-07-2025";
        i2.time = "5:00 PM";
        i2.numberOfGuests = 50;
        i2.isRsvpRequired = false;
        System.out.println("Occasion: " + i2.occasion);
        System.out.println("Host Name: " + i2.hostName);
        System.out.println("Venue: " + i2.venue);
        System.out.println("Date: " + i2.date);
        System.out.println("Time: " + i2.time);
        System.out.println("Number of Guests: " + i2.numberOfGuests);
        System.out.println("RSVP Required: " + i2.isRsvpRequired);

        InvitationCard i3 = new InvitationCard();
        i3.occasion = "Engagement";
        i3.hostName = "Sameer & Riya";
        i3.venue = "Royal Hall";
        i3.date = "01-09-2025";
        i3.time = "7:30 PM";
        i3.numberOfGuests = 120;
        i3.isRsvpRequired = true;
        System.out.println("Occasion: " + i3.occasion);
        System.out.println("Host Name: " + i3.hostName);
        System.out.println("Venue: " + i3.venue);
        System.out.println("Date: " + i3.date);
        System.out.println("Time: " + i3.time);
        System.out.println("Number of Guests: " + i3.numberOfGuests);
        System.out.println("RSVP Required: " + i3.isRsvpRequired);

                InvitationCard i4 = new InvitationCard();
        i4.occasion = "Housewarming";
        i4.hostName = "Vinayak Family";
        i4.venue = "Bengaluru Home";
        i4.date = "15-08-2025";
        i4.time = "11:00 AM";
        i4.numberOfGuests = 100;
        i4.isRsvpRequired = false;
        System.out.println("Occasion: " + i4.occasion);
        System.out.println("Host Name: " + i4.hostName);
        System.out.println("Venue: " + i4.venue);
        System.out.println("Date: " + i4.date);
        System.out.println("Time: " + i4.time);
        System.out.println("Number of Guests: " + i4.numberOfGuests);
        System.out.println("RSVP Required: " + i4.isRsvpRequired);

        InvitationCard i5 = new InvitationCard();
        i5.occasion = "Graduation Party";
        i5.hostName = "Rahul Verma";
        i5.venue = "Club House";
        i5.date = "25-06-2025";
        i5.time = "4:00 PM";
        i5.numberOfGuests = 40;
        i5.isRsvpRequired = true;
        System.out.println("Occasion: " + i5.occasion);
        System.out.println("Host Name: " + i5.hostName);
        System.out.println("Venue: " + i5.venue);
        System.out.println("Date: " + i5.date);
        System.out.println("Time: " + i5.time);
        System.out.println("Number of Guests: " + i5.numberOfGuests);
        System.out.println("RSVP Required: " + i5.isRsvpRequired);

        InvitationCard i6 = new InvitationCard();
        i6.occasion = "Anniversary";
        i6.hostName = "Mr & Mrs Naik";
        i6.venue = "Lalbagh Garden";
        i6.date = "14-02-2025";
        i6.time = "6:30 PM";
        i6.numberOfGuests = 80;
        i6.isRsvpRequired = false;
        System.out.println("Occasion: " + i6.occasion);
        System.out.println("Host Name: " + i6.hostName);
        System.out.println("Venue: " + i6.venue);
        System.out.println("Date: " + i6.date);
        System.out.println("Time: " + i6.time);
        System.out.println("Number of Guests: " + i6.numberOfGuests);
        System.out.println("RSVP Required: " + i6.isRsvpRequired);

        InvitationCard i7 = new InvitationCard();
        i7.occasion = "Farewell";
        i7.hostName = "College Friends";
        i7.venue = "Campus Auditorium";
        i7.date = "30-03-2025";
        i7.time = "2:00 PM";
        i7.numberOfGuests = 150;
        i7.isRsvpRequired = true;
        System.out.println("Occasion: " + i7.occasion);
        System.out.println("Host Name: " + i7.hostName);
        System.out.println("Venue: " + i7.venue);
        System.out.println("Date: " + i7.date);
        System.out.println("Time: " + i7.time);
        System.out.println("Number of Guests: " + i7.numberOfGuests);
        System.out.println("RSVP Required: " + i7.isRsvpRequired);

        InvitationCard i8 = new InvitationCard();
        i8.occasion = "Baby Shower";
        i8.hostName = "Sneha Shetty";
        i8.venue = "Sapphire Banquets";
        i8.date = "10-12-2025";
        i8.time = "12:00 PM";
        i8.numberOfGuests = 60;
        i8.isRsvpRequired = false;
        System.out.println("Occasion: " + i8.occasion);
        System.out.println("Host Name: " + i8.hostName);
        System.out.println("Venue: " + i8.venue);
        System.out.println("Date: " + i8.date);
        System.out.println("Time: " + i8.time);
        System.out.println("Number of Guests: " + i8.numberOfGuests);
        System.out.println("RSVP Required: " + i8.isRsvpRequired);

        InvitationCard i9 = new InvitationCard();
        i9.occasion = "Christening";
        i9.hostName = "Daniel & Priya";
        i9.venue = "St. Paul's Church";
        i9.date = "19-04-2025";
        i9.time = "10:00 AM";
        i9.numberOfGuests = 70;
        i9.isRsvpRequired = true;
        System.out.println("Occasion: " + i9.occasion);
        System.out.println("Host Name: " + i9.hostName);
        System.out.println("Venue: " + i9.venue);
        System.out.println("Date: " + i9.date);
        System.out.println("Time: " + i9.time);
        System.out.println("Number of Guests: " + i9.numberOfGuests);
        System.out.println("RSVP Required: " + i9.isRsvpRequired);

        InvitationCard i10 = new InvitationCard();
        i10.occasion = "Retirement";
        i10.hostName = "Shankar Rao";
        i10.venue = "City Hall";
        i10.date = "05-05-2025";
        i10.time = "3:30 PM";
        i10.numberOfGuests = 110;
        i10.isRsvpRequired = true;
        System.out.println("Occasion: " + i10.occasion);
        System.out.println("Host Name: " + i10.hostName);
        System.out.println("Venue: " + i10.venue);
        System.out.println("Date: " + i10.date);
        System.out.println("Time: " + i10.time);
        System.out.println("Number of Guests: " + i10.numberOfGuests);
        System.out.println("RSVP Required: " + i10.isRsvpRequired);

                InvitationCard i11 = new InvitationCard();
        i11.occasion = "Book Launch";
        i11.hostName = "Author's Circle";
        i11.venue = "Library Auditorium";
        i11.date = "18-09-2025";
        i11.time = "5:00 PM";
        i11.numberOfGuests = 90;
        i11.isRsvpRequired = true;
        System.out.println("Occasion: " + i11.occasion);
        System.out.println("Host Name: " + i11.hostName);
        System.out.println("Venue: " + i11.venue);
        System.out.println("Date: " + i11.date);
        System.out.println("Time: " + i11.time);
        System.out.println("Number of Guests: " + i11.numberOfGuests);
        System.out.println("RSVP Required: " + i11.isRsvpRequired);

        InvitationCard i12 = new InvitationCard();
        i12.occasion = "Welcome Party";
        i12.hostName = "Office HR Team";
        i12.venue = "Sky Lounge";
        i12.date = "07-08-2025";
        i12.time = "6:00 PM";
        i12.numberOfGuests = 75;
        i12.isRsvpRequired = false;
        System.out.println("Occasion: " + i12.occasion);
        System.out.println("Host Name: " + i12.hostName);
        System.out.println("Venue: " + i12.venue);
        System.out.println("Date: " + i12.date);
        System.out.println("Time: " + i12.time);
        System.out.println("Number of Guests: " + i12.numberOfGuests);
        System.out.println("RSVP Required: " + i12.isRsvpRequired);

        InvitationCard i13 = new InvitationCard();
        i13.occasion = "Sangeet";
        i13.hostName = "Raj & Family";
        i13.venue = "Wedding Lawn";
        i13.date = "21-11-2025";
        i13.time = "8:00 PM";
        i13.numberOfGuests = 300;
        i13.isRsvpRequired = true;
        System.out.println("Occasion: " + i13.occasion);
        System.out.println("Host Name: " + i13.hostName);
        System.out.println("Venue: " + i13.venue);
        System.out.println("Date: " + i13.date);
        System.out.println("Time: " + i13.time);
        System.out.println("Number of Guests: " + i13.numberOfGuests);
        System.out.println("RSVP Required: " + i13.isRsvpRequired);

        InvitationCard i14 = new InvitationCard();
        i14.occasion = "Engagement";
        i14.hostName = "Kumar & Family";
        i14.venue = "Green Pearl Banquet";
        i14.date = "12-12-2025";
        i14.time = "7:30 PM";
        i14.numberOfGuests = 150;
        i14.isRsvpRequired = false;
        System.out.println("Occasion: " + i14.occasion);
        System.out.println("Host Name: " + i14.hostName);
        System.out.println("Venue: " + i14.venue);
        System.out.println("Date: " + i14.date);
        System.out.println("Time: " + i14.time);
        System.out.println("Number of Guests: " + i14.numberOfGuests);
        System.out.println("RSVP Required: " + i14.isRsvpRequired);

        InvitationCard i15 = new InvitationCard();
        i15.occasion = "Naming Ceremony";
        i15.hostName = "Lakshmi Narayan";
        i15.venue = "Family Hall";
        i15.date = "03-10-2025";
        i15.time = "10:30 AM";
        i15.numberOfGuests = 100;
        i15.isRsvpRequired = true;
        System.out.println("Occasion: " + i15.occasion);
        System.out.println("Host Name: " + i15.hostName);
        System.out.println("Venue: " + i15.venue);
        System.out.println("Date: " + i15.date);
        System.out.println("Time: " + i15.time);
        System.out.println("Number of Guests: " + i15.numberOfGuests);
        System.out.println("RSVP Required: " + i15.isRsvpRequired);

        InvitationCard i16 = new InvitationCard();
        i16.occasion = "Graduation Ceremony";
        i16.hostName = "Engineering Dept";
        i16.venue = "University Hall";
        i16.date = "09-05-2025";
        i16.time = "2:00 PM";
        i16.numberOfGuests = 400;
        i16.isRsvpRequired = false;
        System.out.println("Occasion: " + i16.occasion);
        System.out.println("Host Name: " + i16.hostName);
        System.out.println("Venue: " + i16.venue);
        System.out.println("Date: " + i16.date);
        System.out.println("Time: " + i16.time);
        System.out.println("Number of Guests: " + i16.numberOfGuests);
        System.out.println("RSVP Required: " + i16.isRsvpRequired);

        InvitationCard i17 = new InvitationCard();
        i17.occasion = "Carnival";
        i17.hostName = "City Club";
        i17.venue = "Central Grounds";
        i17.date = "19-01-2025";
        i17.time = "5:00 PM";
        i17.numberOfGuests = 500;
        i17.isRsvpRequired = true;
        System.out.println("Occasion: " + i17.occasion);
        System.out.println("Host Name: " + i17.hostName);
        System.out.println("Venue: " + i17.venue);
        System.out.println("Date: " + i17.date);
        System.out.println("Time: " + i17.time);
        System.out.println("Number of Guests: " + i17.numberOfGuests);
        System.out.println("RSVP Required: " + i17.isRsvpRequired);

        InvitationCard i18 = new InvitationCard();
        i18.occasion = "Cultural Night";
        i18.hostName = "College Union";
        i18.venue = "Main Stage";
        i18.date = "23-03-2025";
        i18.time = "6:30 PM";
        i18.numberOfGuests = 350;
        i18.isRsvpRequired = false;
        System.out.println("Occasion: " + i18.occasion);
        System.out.println("Host Name: " + i18.hostName);
        System.out.println("Venue: " + i18.venue);
        System.out.println("Date: " + i18.date);
        System.out.println("Time: " + i18.time);
        System.out.println("Number of Guests: " + i18.numberOfGuests);
        System.out.println("RSVP Required: " + i18.isRsvpRequired);

        InvitationCard i19 = new InvitationCard();
        i19.occasion = "Art Exhibition";
        i19.hostName = "Ravi Arts";
        i19.venue = "Gallery 99";
        i19.date = "14-07-2025";
        i19.time = "4:00 PM";
        i19.numberOfGuests = 120;
        i19.isRsvpRequired = false;
        System.out.println("Occasion: " + i19.occasion);
        System.out.println("Host Name: " + i19.hostName);
        System.out.println("Venue: " + i19.venue);
        System.out.println("Date: " + i19.date);
        System.out.println("Time: " + i19.time);
        System.out.println("Number of Guests: " + i19.numberOfGuests);
        System.out.println("RSVP Required: " + i19.isRsvpRequired);

        InvitationCard i20 = new InvitationCard();
        i20.occasion = "Tea Party";
        i20.hostName = "Women's Circle";
        i20.venue = "Garden Pavilion";
        i20.date = "11-04-2025";
        i20.time = "3:00 PM";
        i20.numberOfGuests = 45;
        i20.isRsvpRequired = true;
        System.out.println("Occasion: " + i20.occasion);
        System.out.println("Host Name: " + i20.hostName);
        System.out.println("Venue: " + i20.venue);
        System.out.println("Date: " + i20.date);
        System.out.println("Time: " + i20.time);
        System.out.println("Number of Guests: " + i20.numberOfGuests);
        System.out.println("RSVP Required: " + i20.isRsvpRequired);
    }
}


    