class PipeRunner {

    public static void main(String[] args) {

        Pipe p1 = new Pipe();
        p1.pipeId = 1;
        p1.material = "PVC";
        p1.length = 3.0;
        p1.diameter = 1.5;
        p1.isFlexible = true;
        p1.manufacturer = "Finolex";
        p1.price = 120.0;
        System.out.println("Pipe ID: " + p1.pipeId);
        System.out.println("Material: " + p1.material);
        System.out.println("Length: " + p1.length);
        System.out.println("Diameter: " + p1.diameter);
        System.out.println("Is Flexible: " + p1.isFlexible);
        System.out.println("Manufacturer: " + p1.manufacturer);
        System.out.println("Price: " + p1.price);

        Pipe p2 = new Pipe();
        p2.pipeId = 2;
        p2.material = "Copper";
        p2.length = 2.5;
        p2.diameter = 1.2;
        p2.isFlexible = false;
        p2.manufacturer = "Tata";
        p2.price = 340.5;
        System.out.println("Pipe ID: " + p2.pipeId);
        System.out.println("Material: " + p2.material);
        System.out.println("Length: " + p2.length);
        System.out.println("Diameter: " + p2.diameter);
        System.out.println("Is Flexible: " + p2.isFlexible);
        System.out.println("Manufacturer: " + p2.manufacturer);
        System.out.println("Price: " + p2.price);

        Pipe p3 = new Pipe();
        p3.pipeId = 3;
        p3.material = "Steel";
        p3.length = 4.0;
        p3.diameter = 2.0;
        p3.isFlexible = false;
        p3.manufacturer = "Jindal";
        p3.price = 560.0;
        System.out.println("Pipe ID: " + p3.pipeId);
        System.out.println("Material: " + p3.material);
        System.out.println("Length: " + p3.length);
        System.out.println("Diameter: " + p3.diameter);
        System.out.println("Is Flexible: " + p3.isFlexible);
        System.out.println("Manufacturer: " + p3.manufacturer);
        System.out.println("Price: " + p3.price);

        Pipe p4 = new Pipe();
        p4.pipeId = 4;
        p4.material = "Plastic";
        p4.length = 3.5;
        p4.diameter = 1.0;
        p4.isFlexible = true;
        p4.manufacturer = "Prince";
        p4.price = 85.5;
        System.out.println("Pipe ID: " + p4.pipeId);
        System.out.println("Material: " + p4.material);
        System.out.println("Length: " + p4.length);
        System.out.println("Diameter: " + p4.diameter);
        System.out.println("Is Flexible: " + p4.isFlexible);
        System.out.println("Manufacturer: " + p4.manufacturer);
        System.out.println("Price: " + p4.price);

        Pipe p5 = new Pipe();
        p5.pipeId = 5;
        p5.material = "Aluminium";
        p5.length = 2.8;
        p5.diameter = 0.8;
        p5.isFlexible = false;
        p5.manufacturer = "L&T";
        p5.price = 275.0;
        System.out.println("Pipe ID: " + p5.pipeId);
        System.out.println("Material: " + p5.material);
        System.out.println("Length: " + p5.length);
        System.out.println("Diameter: " + p5.diameter);
        System.out.println("Is Flexible: " + p5.isFlexible);
        System.out.println("Manufacturer: " + p5.manufacturer);
        System.out.println("Price: " + p5.price);

                Pipe p6 = new Pipe();
        p6.pipeId = 6;
        p6.material = "Rubber";
        p6.length = 5.0;
        p6.diameter = 1.4;
        p6.isFlexible = true;
        p6.manufacturer = "Flexo";
        p6.price = 190.0;
        System.out.println("Pipe ID: " + p6.pipeId);
        System.out.println("Material: " + p6.material);
        System.out.println("Length: " + p6.length);
        System.out.println("Diameter: " + p6.diameter);
        System.out.println("Is Flexible: " + p6.isFlexible);
        System.out.println("Manufacturer: " + p6.manufacturer);
        System.out.println("Price: " + p6.price);

        Pipe p7 = new Pipe();
        p7.pipeId = 7;
        p7.material = "Iron";
        p7.length = 6.0;
        p7.diameter = 2.5;
        p7.isFlexible = false;
        p7.manufacturer = "TMT";
        p7.price = 610.0;
        System.out.println("Pipe ID: " + p7.pipeId);
        System.out.println("Material: " + p7.material);
        System.out.println("Length: " + p7.length);
        System.out.println("Diameter: " + p7.diameter);
        System.out.println("Is Flexible: " + p7.isFlexible);
        System.out.println("Manufacturer: " + p7.manufacturer);
        System.out.println("Price: " + p7.price);

        Pipe p8 = new Pipe();
        p8.pipeId = 8;
        p8.material = "HDPE";
        p8.length = 10.0;
        p8.diameter = 3.0;
        p8.isFlexible = true;
        p8.manufacturer = "Astral";
        p8.price = 300.0;
        System.out.println("Pipe ID: " + p8.pipeId);
        System.out.println("Material: " + p8.material);
        System.out.println("Length: " + p8.length);
        System.out.println("Diameter: " + p8.diameter);
        System.out.println("Is Flexible: " + p8.isFlexible);
        System.out.println("Manufacturer: " + p8.manufacturer);
        System.out.println("Price: " + p8.price);

        Pipe p9 = new Pipe();
        p9.pipeId = 9;
        p9.material = "Galvanized Steel";
        p9.length = 4.5;
        p9.diameter = 2.0;
        p9.isFlexible = false;
        p9.manufacturer = "JSW";
        p9.price = 455.0;
        System.out.println("Pipe ID: " + p9.pipeId);
        System.out.println("Material: " + p9.material);
        System.out.println("Length: " + p9.length);
        System.out.println("Diameter: " + p9.diameter);
        System.out.println("Is Flexible: " + p9.isFlexible);
        System.out.println("Manufacturer: " + p9.manufacturer);
        System.out.println("Price: " + p9.price);

        Pipe p10 = new Pipe();
        p10.pipeId = 10;
        p10.material = "Carbon Steel";
        p10.length = 7.0;
        p10.diameter = 3.5;
        p10.isFlexible = false;
        p10.manufacturer = "Welspun";
        p10.price = 750.0;
        System.out.println("Pipe ID: " + p10.pipeId);
        System.out.println("Material: " + p10.material);
        System.out.println("Length: " + p10.length);
        System.out.println("Diameter: " + p10.diameter);
        System.out.println("Is Flexible: " + p10.isFlexible);
        System.out.println("Manufacturer: " + p10.manufacturer);
        System.out.println("Price: " + p10.price);

        Pipe p11 = new Pipe();
        p11.pipeId = 11;
        p11.material = "Glass";
        p11.length = 2.5;
        p11.diameter = 0.9;
        p11.isFlexible = false;
        p11.manufacturer = "Boroglass";
        p11.price = 220.0;
        System.out.println("Pipe ID: " + p11.pipeId);
        System.out.println("Material: " + p11.material);
        System.out.println("Length: " + p11.length);
        System.out.println("Diameter: " + p11.diameter);
        System.out.println("Is Flexible: " + p11.isFlexible);
        System.out.println("Manufacturer: " + p11.manufacturer);
        System.out.println("Price: " + p11.price);

        Pipe p12 = new Pipe();
        p12.pipeId = 12;
        p12.material = "Fiberglass";
        p12.length = 6.2;
        p12.diameter = 2.2;
        p12.isFlexible = true;
        p12.manufacturer = "FiberCo";
        p12.price = 510.0;
        System.out.println("Pipe ID: " + p12.pipeId);
        System.out.println("Material: " + p12.material);
        System.out.println("Length: " + p12.length);
        System.out.println("Diameter: " + p12.diameter);
        System.out.println("Is Flexible: " + p12.isFlexible);
        System.out.println("Manufacturer: " + p12.manufacturer);
        System.out.println("Price: " + p12.price);

        Pipe p13 = new Pipe();
        p13.pipeId = 13;
        p13.material = "Concrete";
        p13.length = 8.0;
        p13.diameter = 4.5;
        p13.isFlexible = false;
        p13.manufacturer = "UltraTech";
        p13.price = 950.0;
        System.out.println("Pipe ID: " + p13.pipeId);
        System.out.println("Material: " + p13.material);
        System.out.println("Length: " + p13.length);
        System.out.println("Diameter: " + p13.diameter);
        System.out.println("Is Flexible: " + p13.isFlexible);
        System.out.println("Manufacturer: " + p13.manufacturer);
        System.out.println("Price: " + p13.price);

        Pipe p14 = new Pipe();
        p14.pipeId = 14;
        p14.material = "Lead";
        p14.length = 2.0;
        p14.diameter = 1.0;
        p14.isFlexible = false;
        p14.manufacturer = "OldMetals";
        p14.price = 200.0;
        System.out.println("Pipe ID: " + p14.pipeId);
        System.out.println("Material: " + p14.material);
        System.out.println("Length: " + p14.length);
        System.out.println("Diameter: " + p14.diameter);
        System.out.println("Is Flexible: " + p14.isFlexible);
        System.out.println("Manufacturer: " + p14.manufacturer);
        System.out.println("Price: " + p14.price);

        Pipe p15 = new Pipe();
        p15.pipeId = 15;
        p15.material = "CPVC";
        p15.length = 3.8;
        p15.diameter = 1.8;
        p15.isFlexible = true;
        p15.manufacturer = "Ashirvad";
        p15.price = 130.0;
        System.out.println("Pipe ID: " + p15.pipeId);
        System.out.println("Material: " + p15.material);
        System.out.println("Length: " + p15.length);
        System.out.println("Diameter: " + p15.diameter);
        System.out.println("Is Flexible: " + p15.isFlexible);
        System.out.println("Manufacturer: " + p15.manufacturer);
        System.out.println("Price: " + p15.price);

        Pipe p16 = new Pipe();
        p16.pipeId = 16;
        p16.material = "Brass";
        p16.length = 1.5;
        p16.diameter = 0.7;
        p16.isFlexible = false;
        p16.manufacturer = "MetFlow";
        p16.price = 350.0;
        System.out.println("Pipe ID: " + p16.pipeId);
        System.out.println("Material: " + p16.material);
        System.out.println("Length: " + p16.length);
        System.out.println("Diameter: " + p16.diameter);
        System.out.println("Is Flexible: " + p16.isFlexible);
        System.out.println("Manufacturer: " + p16.manufacturer);
        System.out.println("Price: " + p16.price);

        Pipe p17 = new Pipe();
        p17.pipeId = 17;
        p17.material = "PEX";
        p17.length = 7.5;
        p17.diameter = 1.1;
        p17.isFlexible = true;
        p17.manufacturer = "Zurn";
        p17.price = 290.0;
        System.out.println("Pipe ID: " + p17.pipeId);
        System.out.println("Material: " + p17.material);
        System.out.println("Length: " + p17.length);
        System.out.println("Diameter: " + p17.diameter);
        System.out.println("Is Flexible: " + p17.isFlexible);
        System.out.println("Manufacturer: " + p17.manufacturer);
        System.out.println("Price: " + p17.price);

        Pipe p18 = new Pipe();
        p18.pipeId = 18;
        p18.material = "Stainless Steel";
        p18.length = 6.6;
        p18.diameter = 2.8;
        p18.isFlexible = false;
        p18.manufacturer = "SSCorp";
        p18.price = 720.0;
        System.out.println("Pipe ID: " + p18.pipeId);
        System.out.println("Material: " + p18.material);
        System.out.println("Length: " + p18.length);
        System.out.println("Diameter: " + p18.diameter);
        System.out.println("Is Flexible: " + p18.isFlexible);
        System.out.println("Manufacturer: " + p18.manufacturer);
        System.out.println("Price: " + p18.price);

        Pipe p19 = new Pipe();
        p19.pipeId = 19;
        p19.material = "Clay";
        p19.length = 3.3;
        p19.diameter = 2.1;
        p19.isFlexible = false;
        p19.manufacturer = "EarthPipe";
        p19.price = 175.0;
        System.out.println("Pipe ID: " + p19.pipeId);
        System.out.println("Material: " + p19.material);
        System.out.println("Length: " + p19.length);
        System.out.println("Diameter: " + p19.diameter);
        System.out.println("Is Flexible: " + p19.isFlexible);
        System.out.println("Manufacturer: " + p19.manufacturer);
        System.out.println("Price: " + p19.price);

        Pipe p20 = new Pipe();
        p20.pipeId = 20;
        p20.material = "ABS";
        p20.length = 4.4;
        p20.diameter = 1.6;
        p20.isFlexible = true;
        p20.manufacturer = "PolyMax";
        p20.price = 165.5;
        System.out.println("Pipe ID: " + p20.pipeId);
        System.out.println("Material: " + p20.material);
        System.out.println("Length: " + p20.length);
        System.out.println("Diameter: " + p20.diameter);
        System.out.println("Is Flexible: " + p20.isFlexible);
        System.out.println("Manufacturer: " + p20.manufacturer);
        System.out.println("Price: " + p20.price);
    }
}


            