class PipeRunner {

    public static void main(String[] args) {

        System.out.println("Main Started");

        Pipe p1 = new Pipe();
        p1.pipeId = 1;
        p1.material = "PVC";
        p1.length = 2.5;
        p1.diameter = 1.5;
        p1.isFlexible = false;
        p1.manufacturer = "Finolex";
        p1.price = 150.0;
        System.out.println("Pipe ID: " + p1.pipeId);
        System.out.println("Material: " + p1.material);
        System.out.println("Length: " + p1.length);
        System.out.println("Diameter: " + p1.diameter);
        System.out.println("Is Flexible: " + p1.isFlexible);
        System.out.println("Manufacturer: " + p1.manufacturer);
        System.out.println("Price: " + p1.price);

        Pipe p2 = new Pipe();
        p2.pipeId = 2;
        p2.material = "Steel";
        p2.length = 3.0;
        p2.diameter = 2.0;
        p2.isFlexible = false;
        p2.manufacturer = "TATA";
        p2.price = 300.0;
        System.out.println("Pipe ID: " + p2.pipeId);
        System.out.println("Material: " + p2.material);
        System.out.println("Length: " + p2.length);
        System.out.println("Diameter: " + p2.diameter);
        System.out.println("Is Flexible: " + p2.isFlexible);
        System.out.println("Manufacturer: " + p2.manufacturer);
        System.out.println("Price: " + p2.price);

        Pipe p3 = new Pipe();
        p3.pipeId = 3;
        p3.material = "Copper";
        p3.length = 1.8;
        p3.diameter = 1.0;
        p3.isFlexible = true;
        p3.manufacturer = "Hindalco";
        p3.price = 500.0;
        System.out.println("Pipe ID: " + p3.pipeId);
        System.out.println("Material: " + p3.material);
        System.out.println("Length: " + p3.length);
        System.out.println("Diameter: " + p3.diameter);
        System.out.println("Is Flexible: " + p3.isFlexible);
        System.out.println("Manufacturer: " + p3.manufacturer);
        System.out.println("Price: " + p3.price);

        Pipe p4 = new Pipe();
        p4.pipeId = 4;
        p4.material = "HDPE";
        p4.length = 2.0;
        p4.diameter = 1.2;
        p4.isFlexible = true;
        p4.manufacturer = "Supreme";
        p4.price = 220.0;
        System.out.println("Pipe ID: " + p4.pipeId);
        System.out.println("Material: " + p4.material);
        System.out.println("Length: " + p4.length);
        System.out.println("Diameter: " + p4.diameter);
        System.out.println("Is Flexible: " + p4.isFlexible);
        System.out.println("Manufacturer: " + p4.manufacturer);
        System.out.println("Price: " + p4.price);

        Pipe p5 = new Pipe();
        p5.pipeId = 5;
        p5.material = "Aluminum";
        p5.length = 3.2;
        p5.diameter = 2.5;
        p5.isFlexible = false;
        p5.manufacturer = "Jindal";
        p5.price = 450.0;
        System.out.println("Pipe ID: " + p5.pipeId);
        System.out.println("Material: " + p5.material);
        System.out.println("Length: " + p5.length);
        System.out.println("Diameter: " + p5.diameter);
        System.out.println("Is Flexible: " + p5.isFlexible);
        System.out.println("Manufacturer: " + p5.manufacturer);
        System.out.println("Price: " + p5.price);

        Pipe p6 = new Pipe();
        p6.pipeId = 6;
        p6.material = "PVC";
        p6.length = 4.0;
        p6.diameter = 1.8;
        p6.isFlexible = true;
        p6.manufacturer = "Prince";
        p6.price = 180.0;
        System.out.println("Pipe ID: " + p6.pipeId);
        System.out.println("Material: " + p6.material);
        System.out.println("Length: " + p6.length);
        System.out.println("Diameter: " + p6.diameter);
        System.out.println("Is Flexible: " + p6.isFlexible);
        System.out.println("Manufacturer: " + p6.manufacturer);
        System.out.println("Price: " + p6.price);

               Pipe p7 = new Pipe();
        p7.pipeId = 7;
        p7.material = "Steel";
        p7.diameter = 6.2;
        p7.length = 9.5;
        p7.color = "Blue";
        p7.usage = "Agriculture";
        p7.isFlexible = false;
        System.out.println("Pipe ID: " + p7.pipeId);
        System.out.println("Material: " + p7.material);
        System.out.println("Diameter: " + p7.diameter);
        System.out.println("Length: " + p7.length);
        System.out.println("Color: " + p7.color);
        System.out.println("Usage: " + p7.usage);
        System.out.println("Is Flexible: " + p7.isFlexible);

        Pipe p8 = new Pipe();
        p8.pipeId = 8;
        p8.material = "PVC";
        p8.diameter = 2.5;
        p8.length = 3.5;
        p8.color = "Grey";
        p8.usage = "Water supply";
        p8.isFlexible = true;
        System.out.println("Pipe ID: " + p8.pipeId);
        System.out.println("Material: " + p8.material);
        System.out.println("Diameter: " + p8.diameter);
        System.out.println("Length: " + p8.length);
        System.out.println("Color: " + p8.color);
        System.out.println("Usage: " + p8.usage);
        System.out.println("Is Flexible: " + p8.isFlexible);

        Pipe p9 = new Pipe();
        p9.pipeId = 9;
        p9.material = "Rubber";
        p9.diameter = 1.8;
        p9.length = 6.5;
        p9.color = "Red";
        p9.usage = "Hydraulics";
        p9.isFlexible = true;
        System.out.println("Pipe ID: " + p9.pipeId);
        System.out.println("Material: " + p9.material);
        System.out.println("Diameter: " + p9.diameter);
        System.out.println("Length: " + p9.length);
        System.out.println("Color: " + p9.color);
        System.out.println("Usage: " + p9.usage);
        System.out.println("Is Flexible: " + p9.isFlexible);

        Pipe p10 = new Pipe();
        p10.pipeId = 10;
        p10.material = "Copper";
        p10.diameter = 1.3;
        p10.length = 2.5;
        p10.color = "Bronze";
        p10.usage = "Refrigeration";
        p10.isFlexible = false;
        System.out.println("Pipe ID: " + p10.pipeId);
        System.out.println("Material: " + p10.material);
        System.out.println("Diameter: " + p10.diameter);
        System.out.println("Length: " + p10.length);
        System.out.println("Color: " + p10.color);
        System.out.println("Usage: " + p10.usage);
        System.out.println("Is Flexible: " + p10.isFlexible);

        Pipe p11 = new Pipe();
        p11.pipeId = 11;
        p11.material = "PVC";
        p11.diameter = 2.8;
        p11.length = 3.0;
        p11.color = "Black";
        p11.usage = "Draining";
        p11.isFlexible = true;
        System.out.println("Pipe ID: " + p11.pipeId);
        System.out.println("Material: " + p11.material);
        System.out.println("Diameter: " + p11.diameter);
        System.out.println("Length: " + p11.length);
        System.out.println("Color: " + p11.color);
        System.out.println("Usage: " + p11.usage);
        System.out.println("Is Flexible: " + p11.isFlexible);

        Pipe p12 = new Pipe();
        p12.pipeId = 12;
        p12.material = "Iron";
        p12.diameter = 5.0;
        p12.length = 7.0;
        p12.color = "Silver";
        p12.usage = "Support";
        p12.isFlexible = false;
        System.out.println("Pipe ID: " + p12.pipeId);
        System.out.println("Material: " + p12.material);
        System.out.println("Diameter: " + p12.diameter);
        System.out.println("Length: " + p12.length);
        System.out.println("Color: " + p12.color);
        System.out.println("Usage: " + p12.usage);
        System.out.println("Is Flexible: " + p12.isFlexible);

        Pipe p13 = new Pipe();
        p13.pipeId = 13;
        p13.material = "Plastic";
        p13.diameter = 1.2;
        p13.length = 2.0;
        p13.color = "White";
        p13.usage = "Cable covering";
        p13.isFlexible = true;
        System.out.println("Pipe ID: " + p13.pipeId);
        System.out.println("Material: " + p13.material);
        System.out.println("Diameter: " + p13.diameter);
        System.out.println("Length: " + p13.length);
        System.out.println("Color: " + p13.color);
        System.out.println("Usage: " + p13.usage);
        System.out.println("Is Flexible: " + p13.isFlexible);

        Pipe p14 = new Pipe();
        p14.pipeId = 14;
        p14.material = "Metal";
        p14.diameter = 4.5;
        p14.length = 6.5;
        p14.color = "Grey";
        p14.usage = "Industrial";
        p14.isFlexible = false;
        System.out.println("Pipe ID: " + p14.pipeId);
        System.out.println("Material: " + p14.material);
        System.out.println("Diameter: " + p14.diameter);
        System.out.println("Length: " + p14.length);
        System.out.println("Color: " + p14.color);
        System.out.println("Usage: " + p14.usage);
        System.out.println("Is Flexible: " + p14.isFlexible);

        Pipe p15 = new Pipe();
        p15.pipeId = 15;
        p15.material = "Rubber";
        p15.diameter = 2.0;
        p15.length = 4.0;
        p15.color = "Green";
        p15.usage = "Gardening";
        p15.isFlexible = true;
        System.out.println("Pipe ID: " + p15.pipeId);
        System.out.println("Material: " + p15.material);
        System.out.println("Diameter: " + p15.diameter);
        System.out.println("Length: " + p15.length);
        System.out.println("Color: " + p15.color);
        System.out.println("Usage: " + p15.usage);
        System.out.println("Is Flexible: " + p15.isFlexible);

        Pipe p16 = new Pipe();
        p16.pipeId = 16;
        p16.material = "Aluminum";
        p16.diameter = 3.0;
        p16.length = 8.0;
        p16.color = "Silver";
        p16.usage = "Ventilation";
        p16.isFlexible = true;
        System.out.println("Pipe ID: " + p16.pipeId);
        System.out.println("Material: " + p16.material);
        System.out.println("Diameter: " + p16.diameter);
        System.out.println("Length: " + p16.length);
        System.out.println("Color: " + p16.color);
        System.out.println("Usage: " + p16.usage);
        System.out.println("Is Flexible: " + p16.isFlexible);

        Pipe p17 = new Pipe();
        p17.pipeId = 17;
        p17.material = "Steel";
        p17.diameter = 6.0;
        p17.length = 10.0;
        p17.color = "Dark Grey";
        p17.usage = "Pipeline";
        p17.isFlexible = false;
        System.out.println("Pipe ID: " + p17.pipeId);
        System.out.println("Material: " + p17.material);
        System.out.println("Diameter: " + p17.diameter);
        System.out.println("Length: " + p17.length);
        System.out.println("Color: " + p17.color);
        System.out.println("Usage: " + p17.usage);
        System.out.println("Is Flexible: " + p17.isFlexible);

        Pipe p18 = new Pipe();
        p18.pipeId = 18;
        p18.material = "Plastic";
        p18.diameter = 2.3;
        p18.length = 3.2;
        p18.color = "Beige";
        p18.usage = "Interior wiring";
        p18.isFlexible = true;
        System.out.println("Pipe ID: " + p18.pipeId);
        System.out.println("Material: " + p18.material);
        System.out.println("Diameter: " + p18.diameter);
        System.out.println("Length: " + p18.length);
        System.out.println("Color: " + p18.color);
        System.out.println("Usage: " + p18.usage);
        System.out.println("Is Flexible: " + p18.isFlexible);

        Pipe p19 = new Pipe();
        p19.pipeId = 19;
        p19.material = "Lead";
        p19.diameter = 1.0;
        p19.length = 1.5;
        p19.color = "Dark Silver";
        p19.usage = "Shielding";
        p19.isFlexible = false;
        System.out.println("Pipe ID: " + p19.pipeId);
        System.out.println("Material: " + p19.material);
        System.out.println("Diameter: " + p19.diameter);
        System.out.println("Length: " + p19.length);
        System.out.println("Color: " + p19.color);
        System.out.println("Usage: " + p19.usage);
        System.out.println("Is Flexible: " + p19.isFlexible);

        Pipe p20 = new Pipe();
        p20.pipeId = 20;
        p20.material = "Copper";
        p20.diameter = 1.5;
        p20.length = 2.0;
        p20.color = "Brown";
        p20.usage = "Electrical";
        p20.isFlexible = true;
        System.out.println("Pipe ID: " + p20.pipeId);
        System.out.println("Material: " + p20.material);
        System.out.println("Diameter: " + p20.diameter);
        System.out.println("Length: " + p20.length);
        System.out.println("Color: " + p20.color);
        System.out.println("Usage: " + p20.usage);
        System.out.println("Is Flexible: " + p20.isFlexible);

        System.out.println("THE MAIN ENDED");

    }
}
