class WeaponRunner {
    public static void main(String[] args) {
        System.out.println("THE MAIN STARTED");

        Weapon w1 = new Weapon();
        w1.weaponId = 1;
        w1.name = "AK-47";
        w1.type = "Ranged";
        w1.weight = 4.3;
        w1.damage = 90;
        w1.isAutomatic = true;
        w1.manufacturer = "Kalashnikov Concern";
        System.out.println("Weapon ID: " + w1.weaponId);
        System.out.println("Name: " + w1.name);
        System.out.println("Type: " + w1.type);
        System.out.println("Weight: " + w1.weight);
        System.out.println("Damage: " + w1.damage);
        System.out.println("Automatic: " + w1.isAutomatic);
        System.out.println("Manufacturer: " + w1.manufacturer);
        System.out.println("--------------------");

        Weapon w2 = new Weapon();
        w2.weaponId = 2;
        w2.name = "Katana";
        w2.type = "Melee";
        w2.weight = 1.2;
        w2.damage = 75;
        w2.isAutomatic = false;
        w2.manufacturer = "Japanese Smiths";
        System.out.println("Weapon ID: " + w2.weaponId);
        System.out.println("Name: " + w2.name);
        System.out.println("Type: " + w2.type);
        System.out.println("Weight: " + w2.weight);
        System.out.println("Damage: " + w2.damage);
        System.out.println("Automatic: " + w2.isAutomatic);
        System.out.println("Manufacturer: " + w2.manufacturer);
        System.out.println("--------------------");

        Weapon w3 = new Weapon();
        w3.weaponId = 3;
        w3.name = "Desert Eagle";
        w3.type = "Ranged";
        w3.weight = 2.0;
        w3.damage = 85;
        w3.isAutomatic = false;
        w3.manufacturer = "Magnum Research";
        System.out.println("Weapon ID: " + w3.weaponId);
        System.out.println("Name: " + w3.name);
        System.out.println("Type: " + w3.type);
        System.out.println("Weight: " + w3.weight);
        System.out.println("Damage: " + w3.damage);
        System.out.println("Automatic: " + w3.isAutomatic);
        System.out.println("Manufacturer: " + w3.manufacturer);
        System.out.println("--------------------");

        Weapon w4 = new Weapon();
        w4.weaponId = 4;
        w4.name = "Machete";
        w4.type = "Melee";
        w4.weight = 1.5;
        w4.damage = 65;
        w4.isAutomatic = false;
        w4.manufacturer = "Cold Steel";
        System.out.println("Weapon ID: " + w4.weaponId);
        System.out.println("Name: " + w4.name);
        System.out.println("Type: " + w4.type);
        System.out.println("Weight: " + w4.weight);
        System.out.println("Damage: " + w4.damage);
        System.out.println("Automatic: " + w4.isAutomatic);
        System.out.println("Manufacturer: " + w4.manufacturer);
        System.out.println("--------------------");

        Weapon w5 = new Weapon();
        w5.weaponId = 5;
        w5.name = "MP5";
        w5.type = "Ranged";
        w5.weight = 2.5;
        w5.damage = 80;
        w5.isAutomatic = true;
        w5.manufacturer = "Heckler & Koch";
        System.out.println("Weapon ID: " + w5.weaponId);
        System.out.println("Name: " + w5.name);
        System.out.println("Type: " + w5.type);
        System.out.println("Weight: " + w5.weight);
        System.out.println("Damage: " + w5.damage);
        System.out.println("Automatic: " + w5.isAutomatic);
        System.out.println("Manufacturer: " + w5.manufacturer);
        System.out.println("--------------------");

        Weapon w6 = new Weapon();
        w6.weaponId = 6;
        w6.name = "Crossbow";
        w6.type = "Ranged";
        w6.weight = 3.0;
        w6.damage = 70;
        w6.isAutomatic = false;
        w6.manufacturer = "TenPoint";
        System.out.println("Weapon ID: " + w6.weaponId);
        System.out.println("Name: " + w6.name);
        System.out.println("Type: " + w6.type);
        System.out.println("Weight: " + w6.weight);
        System.out.println("Damage: " + w6.damage);
        System.out.println("Automatic: " + w6.isAutomatic);
        System.out.println("Manufacturer: " + w6.manufacturer);
        System.out.println("--------------------");

        Weapon w7 = new Weapon();
        w7.weaponId = 7;
        w7.name = "Rapier";
        w7.type = "Melee";
        w7.weight = 1.0;
        w7.damage = 60;
        w7.isAutomatic = false;
        w7.manufacturer = "Spanish Blades";
        System.out.println("Weapon ID: " + w7.weaponId);
        System.out.println("Name: " + w7.name);
        System.out.println("Type: " + w7.type);
        System.out.println("Weight: " + w7.weight);
        System.out.println("Damage: " + w7.damage);
        System.out.println("Automatic: " + w7.isAutomatic);
        System.out.println("Manufacturer: " + w7.manufacturer);
        System.out.println("--------------------");

        Weapon w8 = new Weapon();
        w8.weaponId = 8;
        w8.name = "Glock 17";
        w8.type = "Ranged";
        w8.weight = 0.9;
        w8.damage = 75;
        w8.isAutomatic = false;
        w8.manufacturer = "Glock GmbH";
        System.out.println("Weapon ID: " + w8.weaponId);
        System.out.println("Name: " + w8.name);
        System.out.println("Type: " + w8.type);
        System.out.println("Weight: " + w8.weight);
        System.out.println("Damage: " + w8.damage);
        System.out.println("Automatic: " + w8.isAutomatic);
        System.out.println("Manufacturer: " + w8.manufacturer);
        System.out.println("--------------------");

        Weapon w9 = new Weapon();
        w9.weaponId = 9;
        w9.name = "Tomahawk";
        w9.type = "Melee";
        w9.weight = 1.3;
        w9.damage = 70;
        w9.isAutomatic = false;
        w9.manufacturer = "Custom Blades";
        System.out.println("Weapon ID: " + w9.weaponId);
        System.out.println("Name: " + w9.name);
        System.out.println("Type: " + w9.type);
        System.out.println("Weight: " + w9.weight);
        System.out.println("Damage: " + w9.damage);
        System.out.println("Automatic: " + w9.isAutomatic);
        System.out.println("Manufacturer: " + w9.manufacturer);
        System.out.println("--------------------");

        Weapon w10 = new Weapon();
        w10.weaponId = 10;
        w10.name = "Uzi";
        w10.type = "Ranged";
        w10.weight = 3.5;
        w10.damage = 85;
        w10.isAutomatic = true;
        w10.manufacturer = "Israel Military Industries";
        System.out.println("Weapon ID: " + w10.weaponId);
        System.out.println("Name: " + w10.name);
        System.out.println("Type: " + w10.type);
        System.out.println("Weight: " + w10.weight);
        System.out.println("Damage: " + w10.damage);
        System.out.println("Automatic: " + w10.isAutomatic);
        System.out.println("Manufacturer: " + w10.manufacturer);
        System.out.println("--------------------");

        Weapon w11 = new Weapon();
        w11.weaponId = 11;
        w11.name = "Spear";
        w11.type = "Melee";
        w11.weight = 2.5;
        w11.damage = 65;
        w11.isAutomatic = false;
        w11.manufacturer = "Ancient Weapons Co.";
        System.out.println("Weapon ID: " + w11.weaponId);
        System.out.println("Name: " + w11.name);
        System.out.println("Type: " + w11.type);
        System.out.println("Weight: " + w11.weight);
        System.out.println("Damage: " + w11.damage);
        System.out.println("Automatic: " + w11.isAutomatic);
        System.out.println("Manufacturer: " + w11.manufacturer);
        System.out.println("--------------------");

        Weapon w12 = new Weapon();
        w12.weaponId = 12;
        w12.name = "Revolver";
        w12.type = "Ranged";
        w12.weight = 1.1;
        w12.damage = 80;
        w12.isAutomatic = false;
        w12.manufacturer = "Smith & Wesson";
        System.out.println("Weapon ID: " + w12.weaponId);
        System.out.println("Name: " + w12.name);
        System.out.println("Type: " + w12.type);
        System.out.println("Weight: " + w12.weight);
        System.out.println("Damage: " + w12.damage);
        System.out.println("Automatic: " + w12.isAutomatic);
        System.out.println("Manufacturer: " + w12.manufacturer);
        System.out.println("--------------------");

        Weapon w13 = new Weapon();
        w13.weaponId = 13;
        w13.name = "Battle Axe";
        w13.type = "Melee";
        w13.weight = 3.2;
        w13.damage = 90;
        w13.isAutomatic = false;
        w13.manufacturer = "Viking Arms";
        System.out.println("Weapon ID: " + w13.weaponId);
        System.out.println("Name: " + w13.name);
        System.out.println("Type: " + w13.type);
        System.out.println("Weight: " + w13.weight);
        System.out.println("Damage: " + w13.damage);
        System.out.println("Automatic: " + w13.isAutomatic);
        System.out.println("Manufacturer: " + w13.manufacturer);
        System.out.println("--------------------");

        Weapon w14 = new Weapon();
        w14.weaponId = 14;
        w14.name = "Sniper Rifle";
        w14.type = "Ranged";
        w14.weight = 6.5;
        w14.damage = 95;
        w14.isAutomatic = false;
        w14.manufacturer = "Remington";
        System.out.println("Weapon ID: " + w14.weaponId);
        System.out.println("Name: " + w14.name);
        System.out.println("Type: " + w14.type);
        System.out.println("Weight: " + w14.weight);
        System.out.println("Damage: " + w14.damage);
        System.out.println("Automatic: " + w14.isAutomatic);
        System.out.println("Manufacturer: " + w14.manufacturer);
        System.out.println("--------------------");

        Weapon w15 = new Weapon();
        w15.weaponId = 15;
        w15.name = "Flamethrower";
        w15.type = "Ranged";
        w15.weight = 8.0;
        w15.damage = 100;
        w15.isAutomatic = true;
        w15.manufacturer = "Military Tech";
        System.out.println("Weapon ID: " + w15.weaponId);
        System.out.println("Name: " + w15.name);
        System.out.println("Type: " + w15.type);
        System.out.println("Weight: " + w15.weight);
        System.out.println("Damage: " + w15.damage);
        System.out.println("Automatic: " + w15.isAutomatic);
        System.out.println("Manufacturer: " + w15.manufacturer);
        System.out.println("--------------------");

        Weapon w16 = new Weapon();
        w16.weaponId = 16;
        w16.name = "Halberd";
        w16.type = "Melee";
        w16.weight = 4.0;
        w16.damage = 85;
        w16.isAutomatic = false;
        w16.manufacturer = "Medieval Weapons Ltd";
        System.out.println("Weapon ID: " + w16.weaponId);
        System.out.println("Name: " + w16.name);
        System.out.println("Type: " + w16.type);
        System.out.println("Weight: " + w16.weight);
        System.out.println("Damage: " + w16.damage);
        System.out.println("Automatic: " + w16.isAutomatic);
        System.out.println("Manufacturer: " + w16.manufacturer);
        System.out.println("--------------------");

        Weapon w17 = new Weapon();
        w17.weaponId = 17;
        w17.name = "Crossbow Pistol";
        w17.type = "Ranged";
        w17.weight = 2.2;
        w17.damage = 70;
        w17.isAutomatic = false;
        w17.manufacturer = "PistolTech";
        System.out.println("Weapon ID: " + w17.weaponId);
        System.out.println("Name: " + w17.name);
        System.out.println("Type: " + w17.type);
        System.out.println("Weight: " + w17.weight);
        System.out.println("Damage: " + w17.damage);
        System.out.println("Automatic: " + w17.isAutomatic);
        System.out.println("Manufacturer: " + w17.manufacturer);
        System.out.println("--------------------");

        Weapon w18 = new Weapon();
        w18.weaponId = 18;
        w18.name = "Claymore";
        w18.type = "Melee";
        w18.weight = 3.7;
        w18.damage = 90;
        w18.isAutomatic = false;
        w18.manufacturer = "Scottish Arms";
        System.out.println("Weapon ID: " + w18.weaponId);
        System.out.println("Name: " + w18.name);
        System.out.println("Type: " + w18.type);
        System.out.println("Weight: " + w18.weight);
        System.out.println("Damage: " + w18.damage);
        System.out.println("Automatic: " + w18.isAutomatic);
        System.out.println("Manufacturer: " + w18.manufacturer);
        System.out.println("--------------------");

        Weapon w19 = new Weapon();
        w19.weaponId = 19;
        w19.name = "Taser";
        w19.type = "Ranged";
        w19.weight = 0.5;
        w19.damage = 40;
        w19.isAutomatic = false;
        w19.manufacturer = "StunTech";
        System.out.println("Weapon ID: " + w19.weaponId);
        System.out.println("Name: " + w19.name);
        System.out.println("Type: " + w19.type);
        System.out.println("Weight: " + w19.weight);
        System.out.println("Damage: " + w19.damage);
        System.out.println("Automatic: " + w19.isAutomatic);
        System.out.println("Manufacturer: " + w19.manufacturer);
        System.out.println("--------------------");

        Weapon w20 = new Weapon();
        w20.weaponId = 20;
        w20.name = "Grenade";
        w20.type = "Explosive";
        w20.weight = 0.4;
        w20.damage = 100;
        w20.isAutomatic = false;
        w20.manufacturer = "Ordnance Corp";
        System.out.println("Weapon ID: " + w20.weaponId);
        System.out.println("Name: " + w20.name);
        System.out.println("Type: " + w20.type);
        System.out.println("Weight: " + w20.weight);
        System.out.println("Damage: " + w20.damage);
        System.out.println("Automatic: " + w20.isAutomatic);
        System.out.println("Manufacturer: " + w20.manufacturer);
        System.out.println("--------------------");

        System.out.println("THE MAIN ENDED");
    }
}